(function(g){var window=this;'use strict';var Es=function(n,q){return q?n.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},swR=function(n){return g.rq(n)||n.G("web_enable_caption_language_preference_stickiness")},hR=function(n){var q={languageCode:n.languageCode,
languageName:n.languageName,displayName:g.dt(n),kind:n.kind,name:n.name,id:n.id,is_servable:n.X,is_default:n.isDefault,is_translateable:n.isTranslateable,vss_id:n.vssId};n.xtags&&(q.xtags=n.xtags);n.captionId&&(q.captionId=n.captionId);n.translationLanguage&&(q.translationLanguage=n.translationLanguage);return q},Xpm=function(n,q){var M=new g.kW;
M.languageCode=n.languageCode;M.languageName=n.languageName;M.name=n.name;M.displayName=n.displayName;M.kind=n.kind;M.isDefault=!1;M.X=n.X;M.isTranslateable=n.isTranslateable;M.vssId=n.vssId;M.url=n.url;M.translationLanguage=q;n.xtags&&(M.xtags=n.xtags);n.captionId&&(M.captionId=n.captionId);return M},jw1=function(n,q){var M,t,c;
return g.V1(function(Y){if(Y.X==1)return M=n+"|"+q,g.B(Y,g.Oc(),2);if(Y.X!=3){t=Y.W;if(!t)throw g.S7("gct");return g.B(Y,g.SB(t),3)}c=Y.W;return Y.return(c.get("captions",M))})},SrC=function(n,q,M){jw1(n,q).then(function(t){t&&M(t.trackData,new g.kW(t.metadata))})},ISs=function(n){var q=q||0;
return function(){return n.apply(this,Array.prototype.slice.call(arguments,0,q))}},Wx=function(n,q,M){g.D.call(this);
this.X=null;this.J=!1;this.S=n;this.j=M;this.W=q||window;this.Z=(0,g.fQ)(this.M$,this)},yk=function(n){n.isActive()||n.start()},fSs=function(n){n=n.W;
return n.requestAnimationFrame||n.webkitRequestAnimationFrame||n.mozRequestAnimationFrame||n.oRequestAnimationFrame||n.msRequestAnimationFrame||null},HAa=function(n){n=n.W;
return n.cancelAnimationFrame||n.cancelRequestAnimationFrame||n.webkitCancelRequestAnimationFrame||n.mozCancelRequestAnimationFrame||n.oCancelRequestAnimationFrame||n.msCancelRequestAnimationFrame||null},Xo=function(n){if(!LoC.test(n))throw Error("'"+n+"' is not a valid hex color");
n.length==4&&(n=n.replace(Psu,"#$1$1$2$2$3$3"));n=n.toLowerCase();n=parseInt(n.slice(1),16);return[n>>16,n>>8&255,n&255]},vas=function(){var n=void 0;
n=n===void 0?{}:n;var q="suggest_correction"in g.PQ?g.PQ.suggest_correction:"Edit caption";q=q||"";var M={},t;for(t in n){M={MF:M.MF};M.MF=t;var c=function(Y){return function(){return String(n[Y.MF])}}(M);
q=q.replace(new RegExp("\\$\\{"+M.MF+"\\}","gi"),c);q=q.replace(new RegExp("\\$"+M.MF,"gi"),c)}return q},jM=function(){return g.lQ("yt-player-caption-display-settings")},TCd=function(){this.Z=[];
this.W=[]},SM=function(n,q){switch(q.kind){case "asr":lS_(q,n.Z);
break;default:lS_(q,n.W)}},lS_=function(n,q){g.SL(q,function(M){return n.equals(M)})||q.push(n)},I3=function(n){g.D.call(this);
this.zs=n;this.W=new TCd;this.Z=null;this.j=[];this.N=[]},fZ=function(n,q,M){I3.call(this,n);
this.videoData=q;this.audioTrack=M;this.X=null;this.J=!1;this.j=q.wA;this.N=q.dF;this.J=g.bG(q)},UQR=function(n,q,M){g.V1(function(t){n.X=g.nL(q,M);
g.uf(t)})},Hx=function(){this.segments=[]},uSa=function(n,q){var M=g.FV(n.segments,q);
M>=0||M<0&&(-M-1)%2===1||(M=-M-1,M>0&&q-n.segments[M-1]===1&&M<n.segments.length&&n.segments[M]-q===1?(g.v7(n.segments,M),g.v7(n.segments,M-1)):M>0&&q-n.segments[M-1]===1?n.segments[M-1]=q:M<n.segments.length&&n.segments[M]-q===1?n.segments[M]=q:(g.DR(n.segments,M,0,q),g.DR(n.segments,M+1,0,q)))},LZ=function(n,q,M,t,c,Y){g.D.call(this);
this.policy=n;this.player=q;this.U=M;this.N=t;this.j=c;this.T=Y;this.J=new Hx;this.S=-1;this.W=this.Z=this.X=null;this.Wb=0;this.D=new g.xD(this.u2,1E3,this);this.events=new g.O_(this);g.A(this,this.D);g.A(this,this.events);this.events.RL(q,"SEEK_COMPLETE",this.XO);this.XO();this.u2()},BCs=function(n){return n.X&&n.X.S?n.X.S+n.player.Si()<n.player.getCurrentTime():!1},DQu=function(n,q){if(n.policy.c_&&n.player.wT()){var M=g.SV(q,n.policy,{});
M.set("pot",n.player.wT());M=M.uY()}else M=g.SV(q,n.policy,{}).uY();var t={format:"RAW",withCredentials:!0};if(n.policy.qm){t.method="POST";var c=q.J;c&&Object.keys(c).length>0?t.postBody=g.De(c,g.s6):t.postBody=(0,g.LS)([120,0])}n.j&&(t.responseType="arraybuffer");var Y=++n.Wb,G=(0,g.R)();n.W=g.KL(M,t,3,100,-1,function(k){k.errorCode==="net.timeout"&&n.player.K("capnt",{rn:Y++})}).then(function(k){if(n.policy.yV&&Y%100===1){var b=(0,g.R)();
n.player.K("caprsp",{rn:Y,ms:b-G,kb:(k.xhr.responseText.length/1024).toFixed()})}a:{k=k.xhr;n.pm();if(n.Z){var d=!(n.j?k.response:k.responseText)||k.status>=400;if(b=g.Tl_(k)){k=g.SV(n.Z,n.policy,{});n.Z.Ik(k,b);DQu(n,n.Z);break a}if(d)n.player.K("capfail",{status:k.status});else{var N;g.FJ("fcb_r",(0,g.R)(),((N=n.player.getVideoData())==null?void 0:N.T)||"");N=n.Z.Pb[0];b=N.ut;n.N!=null&&n.S!==b&&(n.j?n.N(k.response,(N.startTime+n.player.Si())*1E3):n.N(k.responseText,(N.startTime+n.player.Si())*
1E3),n.S=b)}}n.Z=null;n.W=null}}).m8(function(k){n.Z=null;
n.W=null;var b;n.player.K("capfail",{rn:Y,status:(b=k.xhr)==null?void 0:b.status})});
n.Z=q;uSa(n.J,n.Z.Pb[0].ut)},Px=function(n,q){I3.call(this,q);
this.X=n;this.Q1=q;this.J=null;this.S=!1;this.logger=new g.u_("caps");this.D=g.v8(this.Q1,this.X)},mQC=function(n,q){var M=[],t;
for(t in n.X.X)if(n.X.X.hasOwnProperty(t)){var c=n.X.X[t];if(g.T6(c,q||null)){var Y=c.info.id,G=Y,k="."+Y,b="",d="";if(c=c.info.captionTrack)Y=c.languageCode,G=c.displayName,k=c.vssId,b=c.kind,d=c.id;else{c=Y;var N=g.HwU.get(c);N==null&&(N=AHC[c]||AHC[c.replace(/-/g,"_")],g.HwU.set(c,N));c=N;G=c||G}M.push(new g.kW({id:t,languageCode:Y,languageName:G,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:k,kind:b,captionId:d}))}}return M},$Qf=function(n,q){return q!=null&&q in n.X.X?n.X.X[q]:null},
Fof=function(n,q,M){var t=[],c;
for(c in n.X.X)if(n.X.X.hasOwnProperty(c)){var Y=n.X.X[c];if(g.T6(Y,M||null)){var G=Y.info.captionTrack;G&&G.languageCode===q&&t.push(Y)}}return t.length?t[0]:null},vx=function(n,q,M,t,c,Y){I3.call(this,n);
this.videoId=M;this.S=c;this.eventId=Y;this.D={};this.X=null;n=t||g.Pk(q).hl||"";n=n.split("_").join("-");this.J=g.TH(q,{hl:n})},TI=function(n){if(typeof DOMParser!="undefined")return g.Vn(new DOMParser,g.wS(n),"application/xml");
throw Error("Your browser does not support loading xml documents");},l5=function(n,q,M,t,c,Y,G,k,b,d){var N=d.isInline()&&!0,O={};
Object.assign(O,q);Object.assign(O,n.params);Object.assign(O,M);var e={};Object.assign(e,q.kQ);n.params.kQ&&Object.assign(e,n.params.kQ);Object.assign(e,M.kQ);N&&(O.windowOpacity=.6,e.backgroundOpacity=0);O.kQ=e;var E=O.Fb===1,h=[{V:"span",Xy:"captions-text",rJ:{style:"word-wrap: normal; display: block;"}}],f,P,v;(k=k.md("caption_edit_on_hover")&&((f=d.getVideoData().getPlayerResponse())==null?void 0:(P=f.captions)==null?void 0:(v=P.playerCaptionsTracklistRenderer)==null?void 0:v.openTranscriptCommand))&&
h.unshift({V:"button",Xy:"caption-edit",rJ:{tabindex:"0","aria-label":vas()},jX:[{V:"svg",rJ:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},jX:[{V:"path",rJ:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.ql.call(this,{V:"div",Xy:"caption-window",rJ:{id:"caption-window-"+n.id,dir:E?"rtl":"ltr",tabindex:"0",lang:O.lang},jX:h});
var u=this;this.D=[];this.gJ=!1;this.W=n;this.aL=this.Fy=null;this.lz=Y;this.iz=G;this.N=null;this.maxWidth=Y*.96;this.maxHeight=G*.96;this.X=O;this.xQ=M;this.Wb=q;this.j=this.Dk("captions-text");this.cg=this.j.style.getPropertyValue("box-decoration-break")!==""||this.j.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Cm=ZAm(t,c,Y,G);this.vg=b;k&&(this.S=this.Dk("caption-edit"),this.RL(this.S,"click",function(){u.vg()}));
this.type=0;this.Nm=this.Cm*aSu(e);this.d7=N;n=new g.qW(this.element,!0);g.A(this,n);n.subscribe("dragstart",this.Z9,this);n.subscribe("dragmove",this.uu,this);n.subscribe("dragend",this.W8,this);this.Ex=this.Hb=this.Fh=this.Xh=0;n="";this.X.windowOpacity&&(n=Xo(this.X.windowColor),n="rgba("+n[0]+","+n[1]+","+n[2]+","+this.X.windowOpacity+")");q={"background-color":n,display:this.X.isVisible===!1?"none":"","text-align":R9a[this.X.textAlign]};this.cg&&(q["border-radius"]=n?this.Nm/8+"px":"");(this.J=
this.W.params.Fb===2||this.W.params.Fb===3)&&oaa(this,this.element);g.SP(this.element,q);if(N){var z;(z=this.element.parentElement)==null||z.style.setProperty("--caption-window-color",n)}switch(this.X.Tp){case 0:case 1:case 2:g.Yi(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Yi(this.element,"ytp-caption-window-bottom")}},oaa=function(n,q){var M="vertical-rl";
n.X.zm===1&&(M="vertical-lr");g.Xh&&(M=M==="vertical-lr"?"tb-lr":"tb-rl");g.SP(q,"-o-writing-mode",M);g.SP(q,"-webkit-writing-mode",M);g.SP(q,"writing-mode",M);g.SP(q,"text-orientation","upright");g.Yi(q,"ytp-vertical-caption");n.W.params.Fb===3&&(g.SP(q,"text-orientation",""),g.SP(q,"transform","rotate(180deg)"))},aSu=function(n){var q=1+.25*(n.fontSizeIncrement||0);
if(n.offset===0||n.offset===2)q*=.8;return q},wps=function(n,q){var M={},t=q.background?q.background:n.X.kQ.background;
if(q.backgroundOpacity!=null||q.background){var c=q.backgroundOpacity!=null?q.backgroundOpacity:n.X.kQ.backgroundOpacity;t=Xo(t);M.background="rgba("+t[0]+","+t[1]+","+t[2]+","+c+")";n.cg&&(M["box-decoration-break"]="clone",M["border-radius"]=n.Nm/8+"px")}if(q.fontSizeIncrement!=null||q.offset!=null)M["font-size"]=n.Cm*aSu(q)+"px";t=1;c=q.color||n.X.kQ.color;if(q.color||q.textOpacity!=null)c=Xo(c),t=q.textOpacity==null?n.X.kQ.textOpacity:q.textOpacity,c="rgba("+c[0]+","+c[1]+","+c[2]+","+t+")",M.color=
c,M.fill=c;var Y=q.charEdgeStyle;Y===0&&(Y=void 0);if(Y){c="rgba(34, 34, 34, "+t+")";var G="rgba(204, 204, 204, "+t+")";q.m2&&(G=c=q.m2);var k=n.Cm/16/2,b=Math.max(k,1),d=Math.max(2*k,1),N=Math.max(3*k,1),O=Math.max(5*k,1);t=[];switch(Y){case 4:for(;N<=O;N+=k)t.push(d+"px "+d+"px "+N+"px "+c);break;case 1:d=window.devicePixelRatio>=2?.5:1;for(Y=b;Y<=N;Y+=d)t.push(Y+"px "+Y+"px "+c);break;case 2:t.push(b+"px "+b+"px "+G);t.push("-"+b+"px -"+b+"px "+c);break;case 3:for(N=0;N<5;N++)t.push("0 0 "+d+"px "+
c)}M["text-shadow"]=t.join(", ")}c="";switch(q.fontFamily){case 1:c='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:c='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:c='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:c='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:c='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:c=g.IE()?'"Carrois Gothic SC", sans-serif-smallcaps':
'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:c='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}c&&(M["font-family"]=c);c=q.offset;c==null&&(c=n.X.kQ.offset);switch(c){case 0:M["vertical-align"]="sub";break;case 2:M["vertical-align"]="super"}q.fontFamily===7&&(M["font-variant"]="small-caps");q.bold&&(M["font-weight"]="bold");q.italic&&(M["font-style"]="italic");q.underline&&(M["text-decoration"]="underline");q.K5&&(M.visibility="hidden");
q.JS===1&&n.J&&(M["text-combine-upright"]="all",M["text-orientation"]="mixed",c=g.e8||g.Xt,n.W.params.Fb===3?M.transform=c?"rotate(90deg)":"rotate(180deg)":c&&(M.transform="rotate(-90deg)"));if(q.textEmphasis===1||q.textEmphasis===2||q.textEmphasis===3||q.textEmphasis===4||q.textEmphasis===5)if(g.e8)M["font-weight"]="bold";else switch(M["text-emphasis-style"]="filled circle",M["text-emphasis-color"]="currentcolor",M["webkit-text-emphasis"]="filled circle",q.textEmphasis){case 4:case 3:M["text-emphasis-position"]=
"under left";M["webkit-text-emphasis-position"]="under left";break;case 5:case 2:M["text-emphasis-position"]="over right",M["webkit-text-emphasis-position"]="over right"}return M},Us=function(n){n=n.split("px");
return n.length>0?(n=Number(n[0]))?n:0:0},z9m=function(n){n.N=g.wJ("SPAN");
g.SP(n.N,{display:"block"});g.Yi(n.N,"caption-visual-line");n.j.appendChild(n.N)},JHd=function(n,q){var M=g.wJ("SPAN");
g.SP(M,{display:"inline-block","white-space":"pre-wrap"});g.SP(M,wps(n,q));M.classList.add("ytp-caption-segment");n.N.appendChild(M);M.previousElementSibling&&(g.SP(M.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.SP(M,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return M},VJR=function(n,q,M){n.gJ=n.gJ||!!M;
var t={};Object.assign(t,n.X.kQ);Object.assign(t,M||q.X);Object.assign(t,n.xQ.kQ);(M=!n.N)&&z9m(n);for(var c=n.Fy&&n.aL&&g.lz(t,n.aL)?n.Fy:JHd(n,t),Y=typeof q.text==="string",G=Y?q.text.split("\n"):[q.text],k=0;k<G.length;k++){var b=k>0||!q.append,d=G[k];b&&!M?(z9m(n),c=JHd(n,t)):b&&M&&(M=!1);d&&(c.appendChild(Y?g.zN(d):d),Y||d.tagName!=="RUBY"||d.childElementCount!==4||g.e8||!g.LY(d.children[2],"text-emphasis")||(b=n.J?"padding-right":"padding-top",g.LY(d.children[2],"text-emphasis-position")&&(b=
n.J?"padding-left":"padding-bottom"),g.fY?g.SP(c,b,"1em"):g.SP(c,b,"0.5em")))}n.aL=t;n.Fy=c;n.D.push(q)},ZAm=function(n,q,M,t){var c=q/360*16;
q>=n&&(n=640,t>M*1.3&&(n=480),c=M/n*16);return c},Bx=function(){this.Z=this.time=this.mode=this.W=0;
this.J=new u5(this);this.j=new u5(this);this.X=[];this.clear()},rH_=function(n,q,M){if(n===255&&q===255||!n&&!q)return{qH:n,
W$:q,result:0};n=Csj[n];q=Csj[q];if(n&128){var t;if(t=!(q&128))t=q,t=M.Je()&&M.W$===t;if(t)return{qH:n,W$:q,result:1}}else if(q&128&&1<=n&&n<=31)return{qH:n,W$:q,result:2};return{qH:n,W$:q,result:3}},QwR=function(n,q,M,t){q===255&&M===255||!q&&!M?(++n.Z===45&&n.reset(),n.J.W.clear(),n.j.W.clear()):(n.Z=0,xQJ(n.J,q,M,t))},ppC=function(n,q){n.X.sort(function(c,Y){var G=c.time-Y.time;
return G===0?c.order-Y.order:G});
for(var M=g.T(n.X),t=M.next();!t.done;t=M.next())t=t.value,n.time=t.time,t.type===0?QwR(n,t.zH,t.GH,q):t.type===1&&n.W&496&&xQJ(n.j,t.zH,t.GH,q);n.X.length=0},DM=function(){this.type=0},AR=function(){this.state=this.W$=this.qH=0},nxR=function(){this.timestamp=this.X=0},mL=function(n){this.j=n;
this.Z=[];this.X=this.W=this.row=0;this.style=new DM;for(n=this.J=0;n<=15;n++){this.Z[n]=[];for(var q=0;q<=32;q++)this.Z[n][q]=new nxR}},$S=function(n,q){if(n.style.type===3){for(var M=0,t=0,c=n.j.time+0,Y="",G="",k=c,b=1;b<=15;++b){for(var d=!1,N=t?t:1;N<=32;++N){var O=n.Z[b][N];
if(O.X!==0){M===0&&(M=b,t=N);d=String.fromCharCode(O.X);var e=O.timestamp;e<c&&(c=e);O.timestamp=k;G&&(Y+=G,G="");Y+=d;d=!0}if((O.X===0||N===32)&&d){G="\n";break}else if(t&&!d)break}if(M&&!d)break}Y&&q.J(M,t,c,k,Y)}else for(t=M=0,Y=c=n.j.time+0,G=1;G<=15;++G)for(k="",b=1;b<=32;++b)if(N=n.Z[G][b],O=N.X,O!==0&&(M===0&&(M=G,t=b),d=String.fromCharCode(O),e=N.timestamp,e<=c&&(c=e),k+=d,N.reset()),b===32||O===0)k&&q.J(M,t,c,Y,k),c=Y,k="",t=M=0},cXj=function(n,q){switch(n){case 0:return q5s[(q&127)-32];
case 1:return MCU[q&15];case 2:return ieR[q&31];case 3:return tCm[q&31]}return 0},Fo=function(n){return n.Z[n.row][n.W]},ZM=function(n,q,M){q>=2&&n.W>1&&(--n.W,Fo(n).X=0);
var t=Fo(n);t.timestamp=n.j.time+0;t.X=cXj(q,M);n.W<32&&n.W++},Y5d=function(n,q,M,t){for(var c=0;c<t;c++)for(var Y=0;Y<=32;Y++){var G=n.Z[q+c][Y],k=n.Z[M+c][Y];
G.X=k.X;G.timestamp=k.timestamp}},a3=function(n,q,M){for(var t=0;t<M;t++)for(var c=0;c<=32;c++)n.Z[q+t][c].reset()},R3=function(n){n.row=n.X>0?n.X:1;
n.W=1;a3(n,0,15)},o3=function(n){this.Z=n;
this.j=0;this.style=new DM;this.S=new mL(this.Z);this.D=new mL(this.Z);this.text=new mL(this.Z);this.W=this.S;this.J=this.D;this.X=this.W},wa=function(n,q,M){var t=n.W,c=!1;
switch(n.style.get()){case 4:case 1:case 2:n.style.get()===4&&t.X>0||($S(t,M),R3(n.W),R3(n.J),t.row=15,t.X=q,c=!0)}n.style.set(3);n.X=t;n.X.style=n.style;n.Z.mode=1<<t.J;c?t.W=1:t.X!==q&&(t.X>q?($S(t,M),a3(t,t.row-t.X,q)):t.row<q&&(q=t.X),t.X=q)},GKa=function(n){n.style.set(1);
n.X=n.J;n.X.X=0;n.X.style=n.style;n.Z.mode=1<<n.X.J},KPJ=function(n){n.style.set(4);
n.X=n.text;n.X.style=n.style;n.Z.mode=1<<n.X.J},u5=function(n){this.X=n;
this.j=0;this.Z=new o3(this.X);this.S=new o3(this.X);this.W=new AR;this.J=this.Z},xQJ=function(n,q,M,t){n.W.update();
q=rH_(q,M,n.W);switch(q.result){case 0:return;case 1:case 2:return}var c=q.qH;M=q.W$;if(32<=c||!c)n.X.mode&n.X.W&&(q=c,q&128&&(q=127),M&128&&(M=127),n=n.J.X,q&96&&ZM(n,0,q),M&96&&ZM(n,0,M),q!==0&&M!==0&&n.style.type===3&&$S(n,t));else if(c&16)a:if(!n.W.matches(c,M)&&(q=n.W,q.qH=c,q.W$=M,q.state=2,q=c&8?n.S:n.Z,n.J=q,n.X.mode=1<<(n.j<<2)+(q.j<<1)+(q.style.type===4?1:0),(n.X.mode|1<<(n.j<<2)+(q.j<<1)+(q.style.type!==4?1:0))&n.X.W))if(M&64){t=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(c&7)<<1|M>>5&1];
n=M&16?((M&14)>>1)*4:0;M=q.X;switch(q.style.get()){case 4:t=M.row;break;case 3:if(t!==M.row){if(t<M.X&&(t=M.X,t===M.row))break;var Y=1+M.row-M.X,G=1+t-M.X;Y5d(M,G,Y,M.X);q=Y;c=M.X;G<Y?(Y=G+c-Y,Y>0&&(q+=Y,c-=Y)):(Y=Y+c-G,Y>0&&(c-=Y));a3(M,q,c)}}M.row=t;M.W=n+1}else switch(c&7){case 1:switch(M&112){case 32:ZM(q.X,0,32);break a;case 48:M===57?(t=q.X,Fo(t).X=0,t.W<32&&t.W++):ZM(q.X,1,M&15)}break;case 2:M&32&&ZM(q.X,2,M&31);break;case 3:M&32&&ZM(q.X,3,M&31);break;case 4:case 5:if(32<=M&&M<=47)switch(M){case 32:GKa(q);
break;case 33:t=q.X;t.W>1&&(--t.W,Fo(t).X=0);break;case 36:t=q.X;q=Fo(t);for(n=0;n<=15;n++)for(M=0;M<=32;M++)if(t.Z[n][M]===q){for(;M<=32;M++)t.Z[n][M].reset();break}break;case 37:wa(q,2,t);break;case 38:wa(q,3,t);break;case 39:wa(q,4,t);break;case 40:ZM(q.X,0,32);break;case 41:q.style.set(2);q.X=q.W;q.X.X=0;q.X.style=q.style;q.Z.mode=1<<q.X.J;break;case 42:t=q.text;t.X=15;t.style.set(4);R3(t);KPJ(q);break;case 43:KPJ(q);break;case 44:n=q.W;switch(q.style.get()){case 1:case 2:case 3:$S(n,t)}a3(n,
0,15);break;case 45:b:{n=q.X;switch(q.style.get()){default:case 2:case 1:break b;case 4:if(n.row<15){++n.row;n.W=1;break b}break;case 3:}n.X<2&&(n.X=2,n.row<n.X&&(n.row=n.X));q=n.row-n.X+1;$S(n,t);Y5d(n,q,q+1,n.X-1);a3(n,n.row,1)}break;case 46:a3(q.J,0,15);break;case 47:$S(q.W,t),q.J.updateTime(q.Z.time+0),t=q.J,q.J=q.W,q.W=t,GKa(q)}break;case 7:switch(M){case 33:case 34:case 35:t=q.X,(t.W+=M&3)>32&&(t.W=32)}}},kKf=function(){},zI=function(n,q,M,t,c,Y,G){Y=Y===void 0?!1:Y;
G=G===void 0?null:G;g.OM.call(this,n,n+q,{priority:M,namespace:"captions"});this.windowId=t;this.text=c;this.append=Y;this.X=G},dVC=function(n,q,M,t,c,Y,G){var k=Y[0],b=G[k.getAttribute("p")];
if(b.Hm===1){var d=Y[1],N=Y[2];Y=Y[3];k.getAttribute("t");d.getAttribute("t");N.getAttribute("t");Y.getAttribute("t");k.getAttribute("p");d.getAttribute("p");Y.getAttribute("p");G=G[N.getAttribute("p")];k=bed(k.textContent,d.textContent,N.textContent,Y.textContent,G);return new zI(n,q,c,M,k,t,b)}switch(b.Hm){case 9:case 10:b.textEmphasis=1;break;case 11:b.textEmphasis=2;break;case 12:b.textEmphasis=3;break;case 13:b.textEmphasis=4;break;case 14:b.textEmphasis=5}return new zI(n,q,c,M,k.textContent||
"",t,b)},bed=function(n,q,M,t,c){var Y=g.IE(),G=Y?g.wJ("DIV"):g.wJ("RUBY"),k=g.wJ("SPAN");
k.textContent=n;G.appendChild(k);n=Y?g.wJ("DIV"):g.wJ("RP");n.textContent=q;G.appendChild(n);q=Y?g.wJ("DIV"):g.wJ("RT");q.textContent=M;G.appendChild(q);M=c.Hm;if(M===10||M===11||M===12||M===13||M===14)if(g.SP(q,"text-emphasis-style","filled circle"),g.SP(q,"text-emphasis-color","currentcolor"),g.SP(q,"webkit-text-emphasis","filled circle"),c.Hm===11||c.Hm===13)g.SP(q,"webkit-text-emphasis-position","under left"),g.SP(q,"text-emphasis-position","under left");M=!0;if(c.Hm===4||c.Hm===7||c.Hm===12||
c.Hm===14)g.SP(G,"ruby-position","over"),g.SP(G,"-webkit-ruby-position","before");else if(c.Hm===5||c.Hm===6||c.Hm===11||c.Hm===13)g.SP(G,"ruby-position","under"),g.SP(G,"-webkit-ruby-position","after"),M=!1;c=Y?g.wJ("DIV"):g.wJ("RP");c.textContent=t;G.appendChild(c);Y&&(t=M,g.SP(G,{display:"inline-block",position:"relative"}),Y=G.firstElementChild.nextElementSibling,g.SP(Y,"display","none"),Y=Y.nextElementSibling,g.SP(Y,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.SP(G.lastElementChild,"display","none"),t?(g.SP(G,"padding-top","0.6em"),g.SP(Y,"top","0")):(g.SP(G,"padding-bottom","0.6em"),g.SP(Y,"bottom","0")));return G},JR=function(){g.D.apply(this,arguments)},Vk=function(n,q,M,t,c){g.OM.call(this,n,n+q,{priority:M,
namespace:"captions"});this.id=t;this.params=c;this.X=[]},Noj=function(n){var q="_"+CZ++;
return new Vk(0,0x8000000000000,0,q,n)},ra=function(n){JR.call(this);
this.J=n;this.pens={};this.N={};this.T={};this.j="_"+CZ++;this.D={};this.W=this.X=null;this.S=!0},xS=function(n,q){n=n.getAttribute(q);
if(n!=null)return Number(n)},Qk=function(n,q){n=n.getAttribute(q);
if(n!=null)return n==="1"},pZ=function(n,q){n=xS(n,q);
return n!==void 0?n:null},qg=function(n,q){n=n.getAttribute(q);
if(n!=null)return n2.test(n),n},OeR=function(n,q){var M={},t=q.getAttribute("ws");
Object.assign(M,t?n.T[t]:n.J);n=pZ(q,"mh");n!=null&&(M.Pj=n);n=pZ(q,"ju");n!=null&&(M.textAlign=n);n=pZ(q,"pd");n!=null&&(M.Fb=n);n=pZ(q,"sd");n!=null&&(M.zm=n);n=qg(q,"wfc");n!=null&&(M.windowColor=n);q=xS(q,"wfo");q!==void 0&&(M.windowOpacity=q/255);return M},gxa=function(n,q){var M={},t=q.getAttribute("wp");
t&&Object.assign(M,n.N[t]);n=pZ(q,"ap");n!=null&&(M.Tp=n);n=xS(q,"cc");n!=null&&(M.pR=n);n=xS(q,"ah");n!=null&&(M.PH=n);n=xS(q,"rc");n!=null&&(M.Kx=n);q=xS(q,"av");q!=null&&(M.Vh=q);return M},eXd=function(n,q,M,t){var c={};
Object.assign(c,gxa(n,q));Object.assign(c,OeR(n,q));t?g.lz(c,n.J)?(t=n.j,c=n.J):t="_"+CZ++:t=q.getAttribute("id")||"_"+CZ++;n=xS(q,"t")+M;q=xS(q,"d")||0x8000000000000;if(c.Fb===2||c.Fb===3)M=c.Kx,c.Kx=c.pR,c.pR=M;return new Vk(n,q,0,t,c)},Mg=function(n){JR.call(this);
this.S=n;this.X=new Map;this.J=new Map;this.j=new Map;this.W=new Map},iF=function(n){n=g.kr(Math.round(n),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-n.length)+n},Ex_=function(n,q,M,t,c){t===0&&(t=0x8000000000000);
var Y={};q.wpWinPosId&&Object.assign(Y,n.J.get(q.wpWinPosId));q.wsWinStyleId&&Object.assign(Y,n.j.get(q.wsWinStyleId));n=q.rcRowCount;n!==void 0&&(Y.Kx=n);q=q.ccColCount;q!==void 0&&(Y.pR=q);if(Y.Fb===2||Y.Fb===3)q=Y.Kx,Y.Kx=Y.pR,Y.pR=q;return new Vk(M,t,0,c,Y)},tD=function(n,q,M){I3.call(this,n);
this.videoData=q;this.audioTrack=M;this.j=q.wA},cw=function(n,q,M,t,c,Y,G,k,b,d){l5.call(this,n,q,M,t,c,Y,G,k,b,d);
this.type=1},Yf=function(n,q,M){this.trackData=n;
this.S=M;this.version=this.j=this.Z=this.byteOffset=0;this.W=[];this.X=new DataView(this.trackData)},Gh=function(n){var q=n.byteOffset;
n.byteOffset+=1;return n.X.getUint8(q)},K2=function(n){var q=n.byteOffset;
n.byteOffset+=4;return n.X.getUint32(q)},kf=function(n,q){JR.call(this);
this.W=n;this.J=q;this.track=this.J.languageName==="CC3"?4:0;this.X=new Bx;this.X.W=1<<this.track},WPj=function(n){if(typeof n==="string")return!1;
n=new Yf(n,8,0);return hXJ(n)},hXJ=function(n){if(!(n.byteOffset<n.X.byteLength)||K2(n)!==1380139777)return!1;
n.version=Gh(n);if(n.version>1)return!1;Gh(n);Gh(n);Gh(n);return!0},bF=function(n,q,M,t,c,Y,G,k,b,d){l5.call(this,n,q,M,t,c,Y,G,k,b,d);
var N=this;this.type=2;this.xl=[];this.U=this.T=this.tE=0;this.JE=NaN;this.g7=0;this.hq=null;this.qP=new g.xD(this.B2,433,this);this.S&&(d.createClientVe(this.S,this,167342),this.RL(this.S,"click",function(){d.logClick(N.S)}),n=new g.qW(this.element,!0),g.A(this,n),n.subscribe("hoverstart",function(){d.logVisibility(N.S,!0)},this));
g.Yi(this.element,"ytp-caption-window-rollup");g.A(this,this.qP);g.SP(this.element,"overflow","hidden")},yXu=function(n,q){if(!q)return"";
n.J&&n.W.params.zm!==1&&(q*=-1);return"translate"+(n.J?"X":"Y")+"("+q+"px)"},sbd=function(n){n.xl=Array.from(n.element.getElementsByClassName("caption-visual-line"));
for(var q=n.W.params.Kx,M=0,t=0,c=n.xl.length-1;M<q&&c>-1;){var Y=n.xl[c];t+=n.J?Y.offsetWidth:Y.offsetHeight;M++;c--}n.T=t;q=Math;M=q.max;isNaN(n.JE)&&((t=n.X.pR)?(c=g.wJ("SPAN"),g.QL(c,"\u2013".repeat(t)),g.SP(c,wps(n,n.X.kQ)),n.j.appendChild(c),n.JE=c.offsetWidth,n.j.removeChild(c)):n.JE=0);t=n.j;n.U=M.call(q,n.JE,n.g7,(n.J?t.offsetHeight:t.offsetWidth)+1)},X0a=function(n,q){sbd(n);
var M=n.xl.reduce(function(Y,G){return(n.J?G.offsetWidth:G.offsetHeight)+Y},0);
M=n.T-M;if(M!==n.tE){var t=M>0&&n.tE===0,c=M<n.tE;q||isNaN(M)||t||!c||(g.Yi(n.element,"ytp-rollup-mode"),n.RL(n.element,"transitionend",n.B2));g.SP(n.j,"transform",yXu(n,M));n.tE=M}sbd(n)},d7=function(n,q,M,t){this.Q1=n;
this.Z=q;this.logger=M;this.Wg=t;this.r7=[];this.Gr=[];this.X=null;n=g.Y8(this.Q1.L().experiments,"html5_override_micro_discontinuities_threshold_ms");this.W=n>0?n:10},IhC=function(n,q){n.X=function(M,t){if(M.info.J){var c=M;
if(n.Gr.length>0){for(c=n.Gr.shift();n.Gr.length>0;)c=g.m4(c,n.Gr.shift());c=g.m4(c,M)}if(c){M=c;try{var Y=g.Fq(M)*1E3}catch(d){Y=M.info.startTime*1E3}try{var G=g.Gvk(M)*1E3}catch(d){G=M.info.duration*1E3}if(Y<0||G<0)Y<0&&(Y=M.info.startTime*1E3),G<0&&(G=M.info.duration*1E3);M.info.startTime=Y/1E3;M.info.j=Y/1E3;M.info.duration=G/1E3;M.info.N=G/1E3;Y=n.j(c);G=Y.ut;Y={formatId:Y.formatId,startTimeMs:Y.startTimeMs,durationMs:Y.durationMs,Nv:G,sT:G};G=jbs(n.r7,Y.startTimeMs);var k=(M=G>=0?n.r7[G]:null)?
M.startTimeMs+M.durationMs:0,b=Y.startTimeMs+Y.durationMs;!M||Y.startTimeMs-k>n.W?n.r7.splice(G+1,0,Y):(M.durationMs=Math.max(k,b)-M.startTimeMs,M.sT=Math.max(M.sT,Y.sT));t(n.r7);t=g.AU(c);S5s(n.Z,t.buffer.slice(t.byteOffset,t.byteLength+t.byteOffset),q,c.info.j)}else n.logger.X(350058965,"Empty slice")}else n.Gr.push(M)};
n.Q1.addEventListener("sabrCaptionsDataLoaded",n.X)},jbs=function(n,q){n=g.FV(n,{startTimeMs:q},function(M,t){return M.startTimeMs-t.startTimeMs});
return n>=0?n:-n-2},Ng=function(n,q){I3.call(this,q);
this.X=n;this.Q1=q;this.logger=new g.u_("caps");this.J=this.S=null;this.D=new d7(this.Q1,this,this.logger,this.X.Wg)},S5s=function(n,q,M,t){n.logger.debug(function(){return"SABR captions data received for "+t});
n.S?n.J==null?n.logger.X(350058965,"Null loaded track meta data at captions data received"):M.UA(q,n.J,t*1E3):n.logger.X(350058965,"Null Representation at captions data received")},fhd=function(n,q){var M=[],t;
for(t in n.X.X)if(n.X.X.hasOwnProperty(t)){var c=n.X.X[t];if(g.T6(c,q||null)){var Y=c.info.id,G=Y,k="."+Y,b="",d="";if(c=c.info.captionTrack)Y=c.languageCode,G=c.displayName,k=c.vssId,b=c.kind,d=c.id;M.push(new g.kW({id:t,languageCode:Y,languageName:G,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:k,kind:b,captionId:d}))}}return M},Hek=function(n,q,M){var t=[],c;
for(c in n.X.X)if(n.X.X.hasOwnProperty(c)){var Y=n.X.X[c];if(g.T6(Y,M||null)){var G=Y.info.captionTrack;G&&G.languageCode===q&&t.push(Y)}}return t.length?t[0]:null},LPd=function(n,q){if(!g.jEa(n)||n.X!=null&&g.v8(q,n.X)&&n.X.X.rawcc!=null)return!1;
q=!!n.X&&n.X.isManifestless&&Object.values(n.X.X).some(function(M){return g.T6(M,"386")});
n=!!n.X&&!n.X.isManifestless&&g.Bls(n.X);return q||n},Oj=function(){JR.call(this)},vxf=function(n){var q=Pyj.length;
if(n.byteLength<q)return!1;n=new Uint8Array(n,0,q);for(var M=0;M<q;M++)if(Pyj[M]!==n[M])return!1;return!0},To_=function(n,q,M,t,c,Y,G,k,b){switch(G.tagName){case "b":k.bold=!0;
break;case "i":k.italic=!0;break;case "u":k.underline=!0}for(var d=0;d<G.childNodes.length;d++){var N=G.childNodes[d];if(N.nodeType===3)N=new zI(q,M,t,c.id,N.nodeValue,Y||d>0,g.Pl(k)?void 0:k),b.push(N),c.X.push(N);else{var O={};Object.assign(O,k);To_(n,q,M,t,c,!0,N,O,b)}}},g7=function(n){var q=n.split(":");
n=0;q=g.T(q);for(var M=q.next();!M.done;M=q.next())n=n*60+Number(M.value);return n*1E3},lhd=function(n,q,M,t){t=Object.assign({Pj:0},t);
return new Vk(n,q,M,"_"+CZ++,t)},ev=function(n,q){g.D.call(this);
this.Q1=n;this.Y=q;this.X=null;this.W=this.Q1.Rk();this.logger=new g.u_("caps")},ugu=function(n,q,M){if(typeof q==="string"||WPj(q))return[{trackData:q,
dN:M}];if(typeof q==="string"&&q.substring(0,6)==="WEBVTT"||typeof q!=="string"&&vxf(q))return[{trackData:q,dN:M}];var t=new DataView(q);if(t.byteLength<=8||t.getUint32(4)!==1718909296)return[];var c=g.N4m(t);if(n.W&&c){var Y=g.YOf(c),G=g.GnJ(c);c=c.r4;Y&&c&&n.W.E5(c,Y,G)}n=g.A5(t,1835295092);if(!n||!n.length||!n[0].size)return[];Y=[];for(G=0;G<n.length;G++)c=n[G],c=new Uint8Array(q,c.dataOffset,c.size-(c.dataOffset-c.offset)),c=g.N9(c),Y.push({trackData:c,dN:M+G*1E3});UVj(t,Y,M);return Y=Y.filter(function(k){return!!k.trackData})},
UVj=function(n,q,M){var t=g.L5(n,0,1836476516),c=9E4;
t&&(c=g.Pj(t)||9E4);t=0;for(var Y=g.A5(n,1836019558),G=0;G<Y.length;G++){var k=Y[G];G<q.length&&(k=g.L5(n,k.dataOffset,1953653094))&&(k=g.L5(n,k.dataOffset,1952867444))&&(k=g.Bj(k)/c*1E3,G===0&&(t=k),q[G].dN=k-t+M||M*G*1E3)}},Boa=function(n,q,M){n.X||(n.X=new Oj);
n=n.X.Z(q,M);Math.random()<.01&&g.Tj(Error("Deprecated subtitles format in web player: WebVTT"));return n},DVR=function(n){var q={};
if(n=g.bk(n))q.lang=n,g.z7k.test(n)&&(q.Fb=1);return q},hD=function(n){g.P8.call(this,n);
var q=this;this.Q1=n;this.Fy=[];this.xl={};this.Cm={};this.N=!1;this.J="NONE";this.W=this.T=this.U=this.tE=this.MP=null;this.d7={tB:function(){q.tB()},
UA:function(Y,G,k,b){q.UA(Y,G,k,b)}};
this.X=null;this.Y=this.Q1.L();this.videoData=this.Q1.getVideoData();this.Ex=this.Q1.Kd();this.Z={kQ:{}};this.S={kQ:{}};g.yz(this.videoData)?this.J="OFFLINE":LPd(this.videoData,this.Q1)?this.J="SABR_LIVE":g.sSJ(this.videoData,this.Q1)?this.J="LIVE":this.videoData.captionTracks.length?this.J="INNERTUBE":this.videoData.hG&&(this.J="TTS");this.Nm=this.Y.controlsType==="3";this.Hb=new ev(this.Q1,this.Y);this.gJ=new g.O_(this);this.D=new g.ql({V:"div",Xy:"ytp-caption-window-container",rJ:{id:"ytp-caption-window-container"}});
this.Wb={top:0,right:0,bottom:0,left:0,width:1,height:1};var M=null,t=g.uC("yt-html5-player-modules::subtitlesModuleData");t&&(M=new g.XA(t));this.storage=M;var c;this.Xh=!((c=n.pn())==null||!c.TM());this.j=AXf(this);this.JE=!this.j&&this.Nm&&this.Xh&&(this.J==="LIVE"||this.J==="SABR_LIVE");g.A(this,this.Hb);this.j?this.aL=this.qm=null:(this.qm=new Wx(this.u8,void 0,this),g.A(this,this.qm),this.aL=new g.xD(this.O_,2E3,this),g.A(this,this.aL));g.A(this,this.gJ);g.wL(this.player,this.D.element,4);g.A(this,
this.D);this.j||this.gJ.RL(n,"resize",this.mD);(this.Fh=g.Dw(this.Y)&&!g.MH()&&!this.Q1.isFullscreen()&&!this.j&&!this.JE)&&this.gJ.RL(n,"resize",this.gm);this.gJ.RL(n,"onPlaybackAudioChange",this.Qi);this.gJ.RL(n,g.eW("captions"),function(Y){q.onCueRangeEnter(Y)});
this.gJ.RL(n,"crx_captions",function(Y){q.onCueRangeExit(Y)});
Ej(this,jM()||{});this.player.p8("onCaptionsModuleAvailable")},$Vu=function(n){if(n.Y.g8===1||n.videoData.LU===1||g.cc(n.videoData,"yt:cc")==="alwayson")return!0;
if(n.videoData.captionTracks.length)var q=n.getAudioTrack().W;if(n.Y.g8===2){if(g.rq(n.Y))var M=mVC(n);else if(n.storage)try{M=n.storage.get("module-enabled")}catch(c){n.storage.remove("module-enabled")}else M=null;if(M!=null)return!!M}M=Es(n.player.getAudioTrack(),g.rq(n.Y));var t=g.cc(n.videoData,"yt:cc");if(Ww(n)===void 0){if(M==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return t?t==="on":!0;if(M==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return t==="on"}else return t==="on";return q==="ON"||g.cc(n.videoData,
"yt:cc")==="on"},y4=function(n,q){if(n.X&&(q===void 0||!q)||!n.videoData.captionTracks.length)return!1;
n=n.getAudioTrack();return!!n.X||n.W==="FORCED_ON"},Ww=function(n){var q=void 0,M=g.F0().gZ(65);
if(g.rq(n.Y)&&M!=null){if(mVC(n)!=null)return!1;q=!M}return q},FPd=function(n){return n.Y.G("html5_honor_caption_availabilities_in_audio_track")&&n.J!=="LIVE"&&n.J!=="SABR_LIVE"},Xn=function(n,q){if(!n.W)return null;
if(n.T&&n.T.J)return n.T.J;q=ZeJ(n,q);q=n.W.W.X(q);var M=null;if(swR(n.Y)){var t=n.Q1.isInline()?void 0:g.lQ("yt-player-caption-sticky-language");for(var c=[t,n.videoData.captionsLanguagePreference,n.Y.captionsLanguagePreference,g.cc(n.videoData,"yt:cc_default_lang")],Y=!1,G=0;G<c.length;G++){var k=c[G];if(k){Y=!0;for(var b=0;b<q.length;b++)if(g.bk(q[b])===k)return q[b];for(b=0;b<q.length;b++)if(g.bk(q[b]).split("-")[0]===k.split("-")[0])return q[b]}}if(Y&&n.W&&(c=n.W.j,c.length))for(c=g.T(c),Y=c.next();!Y.done;Y=
c.next())if(Y=Y.value,Y.languageCode===t){M=Y;break}}else for(t=[n.videoData.captionsLanguagePreference,n.Y.captionsLanguagePreference,g.cc(n.videoData,"yt:cc_default_lang")],c=0;c<t.length;c++)for(Y=0;Y<q.length;Y++)if(g.bk(q[Y])===t[c])return q[Y];t=null;n.T&&n.T.Z&&(t=n.T.Z);t||(t=q.find(function(d){return d.isDefault})||null);
t||(t=q[0]||sj(n));t&&M&&g.bk(t).split("-")[0]!==M.languageCode.split("-")[0]&&(t=Xpm(t,M));return t},sj=function(n){return n.T&&n.T.X},jv=function(n){var q=sj(n);
return!!q&&n.X===q},ahs=function(n,q){var M=n.Q1.pn().MM().textTracks;
n=n.X.toString();for(var t=0;t<M.length;t++){var c=M[t];c.id===n&&(q?c.mode!=="showing"&&(c.mode="showing"):c.mode==="showing"&&(c.mode="disabled"))}},Hw=function(n,q,M){n.loaded&&n.unload();
M!=null&&(n.N=M,n.N&&(g.rq(n.Y)?Sv(n,!!q):Iu(n,!!q)));q!==null||y4(n,!0)||n.VA(q,!!q,n.N?"m":"s");n.X=q;y4(n)&&(n.X=sj(n));var t;f2(n,(t=n.X)!=null?t:void 0);n.load()},oxm=function(n,q){if(q instanceof Vk){var M=n.xl[q.id];
M&&M.W!==q&&(M.dispose(),delete n.xl[q.id],M=null);M||(M=RXd(n,q))&&(n.xl[q.id]=M)}else M=q.windowId,n.Cm[M]||(n.Cm[M]=[]),n.Cm[M].push(q)},RXd=function(n,q){var M=w0U(n);
if(!M)return null;var t=n.X?g.bk(n.X):null;t&&g.z7k.test(t)&&(q.params.Fb=1);var c=n.Ex.getPlayerSize();t=c.height*n.Wb.height;c=c.width*n.Wb.width;n.Y.playerStyle!=="google-live"||n.Z.isDefault||Object.assign(q.params,n.Z);switch(q.params.Pj!=null?q.params.Pj:q.X.length>1?1:0){case 1:return new cw(q,n.Z,n.S,M.width,M.height,c,t,n.Y.experiments,n.Xx.bind(n),n.Q1);case 2:return new bF(q,n.Z,n.S,M.width,M.height,c,t,n.Y.experiments,n.Xx.bind(n),n.Q1);default:return new l5(q,n.Z,n.S,M.width,M.height,
c,t,n.Y.experiments,n.Xx.bind(n),n.Q1)}},Ej=function(n,q,M){M=M===void 0?!1:M;
var t=L2.kQ;n.Z={};Object.assign(n.Z,L2);n.Z.kQ={};Object.assign(n.Z.kQ,t);n.S={kQ:{}};var c=q.backgroundOverride?n.S:n.Z,Y=q.background||t.background;n2.test(Y);c.kQ.background=Y;c=q.colorOverride?n.S:n.Z;Y=q.color||t.color;n2.test(Y);c.kQ.color=Y;c=q.windowColorOverride?n.S:n.Z;Y=q.windowColor||L2.windowColor;n2.test(Y);c.windowColor=Y;c=q.backgroundOpacityOverride?n.S:n.Z;Y=q.backgroundOpacity;Y==null&&(Y=t.backgroundOpacity);c.kQ.backgroundOpacity=Y;c=q.fontSizeIncrementOverride?n.S:n.Z;Y=q.fontSizeIncrement;
Y==null&&(Y=t.fontSizeIncrement);c.kQ.fontSizeIncrement=Y;Y=q.fontStyleOverride?n.S:n.Z;c=q.fontStyle;c==null&&(c=t.bold&&t.italic?3:t.bold?1:t.italic?2:0);Y=Y.kQ;switch(c){case 1:Y.bold=!0;delete Y.italic;break;case 2:delete Y.bold;Y.italic=!0;break;case 3:Y.bold=!0;Y.italic=!0;break;default:delete Y.bold,delete Y.italic}c=q.textOpacityOverride?n.S:n.Z;Y=q.textOpacity;Y==null&&(Y=t.textOpacity);c.kQ.textOpacity=Y;c=q.windowOpacityOverride?n.S:n.Z;Y=q.windowOpacity;Y==null&&(Y=L2.windowOpacity);c.windowOpacity=
Y;c=q.charEdgeStyleOverride?n.S:n.Z;Y=q.charEdgeStyle;Y==null&&(Y=t.charEdgeStyle);c.kQ.charEdgeStyle=Y;c=q.fontFamilyOverride?n.S:n.Z;Y=q.fontFamily;Y==null&&(Y=t.fontFamily);c.kQ.fontFamily=Y;n.loaded&&n.mD();M&&g.TY("yt-player-caption-display-settings",q,2592E3)},zXm=function(n,q){if(!n.W)return{};
if(q){g.Pl(q)||n.h1(q.vss_id,"m");if(n.j||!g.jS(q))return;if(g.Pl(q)){Hw(n,null,!0);return}for(var M,t=n.W.W.X(!0),c=0;c<t.length;c++){var Y=t[c];Y.languageCode!==q.languageCode||M&&(Y.languageName!==q.languageName||(Y.captionId||"")!==(q.captionId||"")||g.dt(Y)!==q.displayName)||(M=q.translationLanguage?Xpm(Y,q.translationLanguage):Y)}n.Da(q.position);!M||M===n.X&&n.loaded||(q=g.PH(),t=g.bk(M),q.length&&t===q[q.length-1]||(q.push(t),g.TY("yt-player-caption-language-preferences",q)),swR(n.Y)&&!n.Q1.isInline()&&
g.TY("yt-player-caption-sticky-language",t,2592E3),Hw(n,M,!0))}else return n.loaded&&n.X&&!jv(n)?hR(n.X):{};return""},Pw=function(n,q,M){q&&!n.U?(q=Noj({Fb:1,
lang:"ar"}),n.U=[q,new zI(q.start,q.end-q.start,0,q.id,M!=null?M:"\u062a\u0638\u0647\u0631 \u0627\u0644\u062a\u0631\u062c\u0645\u0629 \u0628\u0627\u0644\u0634\u0643\u0644 \u0627\u0644\u062a\u0627\u0644\u064a")],n.player.aQ(n.U)):!q&&n.U&&(JXC(n,n.U),n.U=null)},JXC=function(n,q){n.player.OC(q);
q=g.T(q);for(var M=q.next();!M.done;M=q.next())g.TZ(n.Fy,M.value);yk(n.qm)},f2=function(n,q){n.Y.G("html5_modify_caption_vss_logging")&&(n.videoData.M2=q)},w0U=function(n){var q=n.Ex.getVideoContentRect(!0).height,M=n.Ex.getVideoContentRect(!0).width;
if(!q||!M)return null;q*=n.Wb.height;M*=n.Wb.width;return{width:M,height:q}},Iu=function(n,q){if(n.storage)try{n.storage.set("module-enabled",q)}catch(M){}},Sv=function(n,q){n.Q1.isInline()||g.TY("yt-player-sticky-caption",q,2592E3)},mVC=function(n){if(!n.Q1.isInline())return g.lQ("yt-player-sticky-caption")},AXf=function(n){var q,M=!((q=n.Q1.pn())==null||!q.E1());
return n.Nm&&M&&n.J!=="LIVE"&&n.J!=="SABR_LIVE"},ZeJ=function(n,q){g.bG(n.videoData)&&(q=!0);
q||(q=n.J==="TTS"?!1:n.J==="INNERTUBE"?!1:!0);return q||n.Y.G("web_deprecate_always_includes_asr_setting")&&g.rq(n.Y)?!0:!!g.F0().gZ(66)};
g.Yz.prototype.FR=g.GU(83,function(){var n=g.ZL(document,"track",void 0,this.X);for(var q=0;q<n.length;q++)g.CP(n[q])});
g.gp.prototype.FR=g.GU(82,function(){this.mediaElement.FR()});
g.Yz.prototype.TM=g.GU(81,function(){return!(!this.X.textTracks||!this.X.textTracks.addEventListener)});
g.gp.prototype.TM=g.GU(80,function(){return this.mediaElement.TM()});
g.Yz.prototype.E1=g.GU(79,function(){return!!this.X.textTracks});
g.gp.prototype.E1=g.GU(78,function(){return this.mediaElement.E1()});
g.Yz.prototype.fF=g.GU(77,function(n){for(var q=0;q<n.length;q++)this.X.appendChild(n[q])});
g.gp.prototype.fF=g.GU(76,function(n){this.mediaElement.fF(n)});
g.UR.prototype.E5=g.GU(75,function(n,q,M){this.Nn.E5(n,q,M)});
g.U1.prototype.E5=g.GU(74,function(n,q,M){this.W.set(n,{zP:q,XR:M})});
g.DK.prototype.E5=g.GU(73,function(n,q,M){this.N.E5(n,q,M)});
g.UR.prototype.S9=g.GU(72,function(n){return this.Nn.S9(n)});
g.DK.prototype.S9=g.GU(71,function(n){var q=2;this.j.has(n)?q=0:g.zg(this,n)&&(q=1);return q});
g.FK.prototype.o2=g.GU(32,function(n){var q=this.app.Hg({playerType:void 0});return q?q.o2(n):!1});
g.rL.prototype.o2=g.GU(31,function(n){return this.C.OT.o2(n)});
g.V3.prototype.o2=g.GU(30,function(n){return this.Oh().some(function(q){return q.namespace===n})});
g.jp.prototype.o2=g.GU(29,function(){return!1});
g.FK.prototype.h1=g.GU(24,function(n,q){this.app.AE().h1(n,q)});
g.rL.prototype.h1=g.GU(23,function(n,q){this.C.h1(n,q)});
g.Kl.prototype.h1=g.GU(22,function(n,q){n=[n,q];g.G3(this,g.d1(this.provider),"cfi",n)});
g.w8.prototype.h1=g.GU(21,function(n,q){this.qoe&&this.qoe.h1(n,q)});
g.Po.prototype.h1=g.GU(20,function(n,q){this.Im.h1(n,q)});
g.jp.prototype.h1=g.GU(19,function(){});
g.FK.prototype.VA=g.GU(18,function(n,q,M){this.app.AE().VA(n,q,M)});
g.rL.prototype.VA=g.GU(17,function(n,q,M){this.C.VA(n,q,M)});
g.Kl.prototype.VA=g.GU(16,function(n,q,M){if(this.qm!==n||this.xQ!==q)q=q==="rawcc"?"":q,M=[n,q,this.qm,M],g.G3(this,g.d1(this.provider),"cfs",M),this.qm=n,this.xQ=q});
g.w8.prototype.VA=g.GU(15,function(n,q,M){this.qoe&&this.qoe.VA(n,q,M)});
g.Po.prototype.VA=g.GU(14,function(n,q,M){this.Im.VA(n,q,M)});
g.jp.prototype.VA=g.GU(13,function(){});
g.yb.prototype.OX=g.GU(8,function(){return this.U});
g.Wy.prototype.OX=g.GU(7,function(){return this.AE().Rk()});
g.FK.prototype.Rk=g.GU(6,function(){return this.app.OX()});
g.rL.prototype.Rk=g.GU(5,function(){return this.C.Rk()});
g.Po.prototype.Rk=g.GU(4,function(){var n;return((n=this.loader)==null?void 0:n.OX())||null});
g.jp.prototype.Rk=g.GU(3,function(){return null});
g.gH.prototype.oS=g.GU(2,function(n){return(n=this.xb(n))?n.X:0});
g.oc.prototype.oS=g.GU(1,function(){return 0});
g.TL(Wx,g.D);g.X=Wx.prototype;g.X.start=function(){this.stop();this.J=!1;var n=fSs(this),q=HAa(this);n&&!q&&this.W.mozRequestAnimationFrame?(this.X=g.Qo(this.W,"MozBeforePaint",this.Z),this.W.mozRequestAnimationFrame(null),this.J=!0):this.X=n&&q?n.call(this.W,this.Z):this.W.setTimeout(ISs(this.Z),20)};
g.X.stop=function(){if(this.isActive()){var n=fSs(this),q=HAa(this);n&&!q&&this.W.mozRequestAnimationFrame?g.Yb(this.X):n&&q?q.call(this.W,this.X):this.W.clearTimeout(this.X)}this.X=null};
g.X.isActive=function(){return this.X!=null};
g.X.M$=function(){this.J&&this.X&&g.Yb(this.X);this.X=null;this.S.call(this.j,g.LQ())};
g.X.wJ=function(){this.stop();Wx.sC.wJ.call(this)};
var Psu=/#(.)(.)(.)/,LoC=/^#(?:[0-9a-f]{3}){1,2}$/i,AHC={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};TCd.prototype.X=function(n){return n?this.W.concat(this.Z):this.W};
g.L(I3,g.D);g.X=I3.prototype;g.X.Go=function(){};
g.X.ql=function(){};
g.X.hP=function(){};
g.X.XH=function(){return""};
g.X.OI=function(){return!1};
g.X.tB=function(n,q){var M=this;if(this.zs.L().G("html5_dispatch_tracklist_loaded_event")){this.Z&&(this.Z.reject(),this.Z=null);var t=[];this.zs.Mm("trackListLoaded",this.W,t,q);t.length?(q=new g.L1,q.promise.then(n.tB,function(){}),this.Z=q,Promise.all(t).then(q.resolve,q.reject).finally(function(){M.Z=null})):n.tB()}else n.tB()};
g.X.wJ=function(){this.Z&&(this.Z.reject(),this.Z=null);this.hP();g.D.prototype.wJ.call(this)};
g.L(fZ,I3);fZ.prototype.Go=function(n,q,M){var t=this;this.pm();q=this.XH(n,q);var c=this.zs.L().G("html5_report_captions_ctmp_qoe"),Y=(0,g.R)();this.hP();UQR(this,q,{format:"RAW",onSuccess:function(G){t.X=null;if(c){var k=(G.responseText.length/1024).toFixed(),b=(0,g.R)();t.videoData.K("capresp",{ms:b-Y,kb:k})}M.UA(G.responseText,n)},
onError:c?function(G){var k;G=(k=G==null?void 0:G.status)!=null?k:0;t.videoData.K("capfail",{status:G})}:void 0,
withCredentials:!0})};
fZ.prototype.ql=function(n){if(this.audioTrack)for(var q=g.T(this.audioTrack.captionTracks),M=q.next();!M.done;M=q.next())SM(this.W,M.value);this.tB(n,this.videoData.videoId)};
fZ.prototype.XH=function(n,q){var M=n.uY(),t={fmt:q};if(q==="srv3"||q==="3"||q==="json3")g.IE()?Object.assign(t,{xorb:2,xobt:1,xovt:1}):Object.assign(t,{xorb:2,xobt:3,xovt:3});n.translationLanguage&&(t.tlang=g.bk(n));this.J&&(t.xosf="1");Object.assign(t,this.zs.L().X);return g.TH(M,t)};
fZ.prototype.hP=function(){this.X&&this.X.abort()};
Hx.prototype.contains=function(n){n=g.FV(this.segments,n);return n>=0||n<0&&(-n-1)%2===1};
Hx.prototype.length=function(){return this.segments.length/2};
g.L(LZ,g.D);g.X=LZ.prototype;g.X.wJ=function(){g.D.prototype.wJ.call(this);this.W&&this.W.cancel()};
g.X.XO=function(){this.seekTo(this.player.getCurrentTime())};
g.X.seekTo=function(n){n-=this.player.Si();var q=this.X;this.X=g.XV(this.U.nR(n).Pb);q!==this.X&&this.T&&this.T()};
g.X.reset=function(){this.J=new Hx;this.S=-1;this.W&&(this.W.cancel(),this.W=null)};
g.X.u2=function(){this.pm();var n;if(n=this.X!=null)n=this.X,n=n.X.Qf(n);if(n&&!this.W&&!(this.X&&this.X.startTime-this.player.getCurrentTime()>30)){n=this.X;n=n.X.Qm(n);var q=n.Pb[0],M;if((M=this.player.getVideoData())==null?0:M.enableServerStitchedDai)if(M=this.player.Rk()){var t=q.X.info.id,c=q.ut,Y=n.Pb[0].j;if(this.policy.qm){if(M=M.PW(Y,c,t,3))n.J=M}else if(t=M.V$(Y,c,t,3))if(M=M.S9(c),M===0)t&&(n.X=new g.Yo(t));else if(M===2){this.D.start();BCs(this)&&this.seekTo(this.player.getCurrentTime());
return}}q.X.index.FJ(q.ut)?(this.J.contains(n.Pb[0].ut)||DQu(this,n),this.X=g.XV(n.Pb)):BCs(this)&&this.seekTo(this.player.getCurrentTime())}this.D.start()};
g.L(Px,I3);g.X=Px.prototype;g.X.Go=function(n,q,M){var t=this;this.hP();q=$Qf(this,n.getId());q||(q=n.languageCode,q=this.X.isManifestless?Fof(this,q,"386"):Fof(this,q));if(q){var c=(q.index.oS(q.index.XJ())-q.index.getStartTime(q.index.XJ()))*1E3,Y=new g.i$C(this.Q1.L());this.J=new LZ(Y,this.Q1,q,function(G,k){M.UA(G,n,k,c)},this.D||g.$J(q.info),function(){t.J&&t.J.reset();
t.S=!0})}};
g.X.OI=function(){var n=this.S;this.S=!1;return n};
g.X.ql=function(n){var q=this.Q1.L().G("html5_fallback_if_rawcc_missing");var M=this.X.X.rawcc!=null;if(!this.D||!M&&q)q=this.X.isManifestless?mQC(this,"386"):mQC(this);else{if(!M){this.logger.X(386248249,"rawcc used but unavailable");return}q=[new g.kW({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.kW({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}q=g.T(q);
for(M=q.next();!M.done;M=q.next())SM(this.W,M.value);n.tB()};
g.X.hP=function(){this.J&&(this.J.dispose(),this.J=null)};
g.X.XH=function(){return""};
g.L(vx,I3);vx.prototype.Go=function(n,q,M){var t=this;this.pm();q=this.XH(n,q);this.hP();this.X=g.nL(q,{format:"RAW",onSuccess:function(c){t.X=null;M.UA(c.responseText,n)},
withCredentials:!0})};
vx.prototype.ql=function(n){var q=this,M=this.J,t={type:"list",tlangs:1,v:this.videoId,vssids:1};this.S&&(t.asrs=1);M=g.TH(M,t);this.hP();this.X=g.nL(M,{format:"RAW",onSuccess:function(c){q.X=null;if((c=c.responseXML)&&c.firstChild){for(var Y=c.getElementsByTagName("track"),G=0;G<Y.length;G++){var k=Y[G],b=k.getAttribute("lang_code"),d=k.getAttribute("lang_translated"),N=k.getAttribute("name"),O=k.getAttribute("kind"),e=k.getAttribute("id"),E=k.getAttribute("lang_default")==="true",h=k.getAttribute("cantran")===
"true";k=k.getAttribute("vss_id");SM(q.W,new g.kW({languageCode:b,languageName:d,name:N,kind:O,id:e,is_servable:!0,is_translateable:h,vss_id:k,is_default:E}))}c=c.getElementsByTagName("target");Y=c.length;for(G=0;G<Y;G++)b={languageCode:c[G].getAttribute("lang_code"),languageName:c[G].getAttribute("lang_translated"),languageOriginal:c[G].getAttribute("lang_original"),id:c[G].getAttribute("id"),isDefault:c[G].getAttribute("lang_default")==="true"},q.D[b.languageCode]=b.languageName,q.j.push(b)}q.tB(n,
q.videoId)},
withCredentials:!0})};
vx.prototype.XH=function(n,q){var M=this.J;q={v:this.videoId,type:"track",lang:n.languageCode,name:n.getName(),kind:n.kind,fmt:q};var t=this.zs.L();t.G("captions_url_add_ei")&&(q.ei=this.eventId);n.translationLanguage&&(q.tlang=g.bk(n));Object.assign(q,t.X);return M=g.TH(M,q)};
vx.prototype.hP=function(){this.X&&this.X.abort()};
var n2=/^#(?:[0-9a-f]{3}){1,2}$/i;var R9a=["left","right","center","justify"];g.L(l5,g.ql);g.X=l5.prototype;g.X.Z9=function(n,q){this.Hb=n;this.Ex=q;var M=g.l$(this.element,this.element.parentElement);this.Xh=n-M.x;this.Fh=q-M.y};
g.X.uu=function(n,q){if(n!==this.Hb||q!==this.Ex){g.cX(this.element,"ytp-dragging")||g.Yi(this.element,"ytp-dragging");var M=g.Dm(this.element);n=n-this.Xh-.02*this.lz;var t=q-this.Fh-.02*this.iz,c=(n+M.width/2)/this.maxWidth*3;c=Math.floor(g.kr(c,0,2));var Y=(t+M.height/2)/this.maxHeight*3;Y=Math.floor(g.kr(Y,0,2));q=c+Y*3;n=(n+c/2*M.width)/this.maxWidth;n=g.kr(n,0,1)*100;M=(t+Y/2*M.height)/this.maxHeight;M=g.kr(M,0,1)*100;this.W.params.Tp=q;this.W.params.Vh=M;this.W.params.PH=n;this.W.params.isDefault=
!1;this.X.Tp=q;this.X.Vh=M;this.X.PH=n;this.X.isDefault=!1;this.Wb.Tp=q;this.Wb.Vh=M;this.Wb.PH=n;this.Wb.isDefault=!1;this.vD()}};
g.X.W8=function(){g.K4(this.element,"ytp-dragging")};
g.X.vD=function(){this.dE(this.D)};
g.X.dE=function(n){var q=this.d7?0:Math.min(this.mO(),this.maxWidth),M=this.C0(),t=this.d7;if(t){var c=getComputedStyle(this.j.parentNode);c=Us(c.borderLeftWidth)+Us(c.borderRightWidth)+Us(c.paddingLeft)+Us(c.paddingRight)}else c=0;var Y=c;c="";this.W.params.Fb===3&&(c="rotate(180deg)");var G=t?"calc(96% - "+Y+"px)":"96%";g.SP(this.element,{top:0,left:0,right:"",bottom:"",width:q?q+"px":"",height:M?M+"px":"","max-width":G,"max-height":G,margin:"",transform:""});this.iW(n);c={transform:c,top:"",left:"",
width:q?q+"px":"",height:M?M+"px":"","max-width":"","max-height":""};var k=this.X.PH*.96+2;G=this.X.Tp;switch(G){case 0:case 3:case 6:(t=this.X.kQ.fontSizeIncrement)&&t>0&&this.X.Fb!==2&&this.X.Fb!==3&&(k=Math.max(k/(1+t*2),2));c.left=k+"%";break;case 1:case 4:case 7:c.left=k+"%";k=this.j.offsetWidth;q||k?(q=q||k+1,c.width=q+"px",c["margin-left"]=t?q/-2-Y/2+"px":q/-2+"px"):c.transform+=" translateX(-50%)";break;case 2:case 5:case 8:c.right=100-k+"%"}t=this.X.Vh*.96+2;switch(G){case 0:case 1:case 2:c.top=
t+"%";break;case 3:case 4:case 5:c.top=t+"%";(M=M||this.element.clientHeight)?(c.height=M+"px",c["margin-top"]=M/-2+"px"):c.transform+=" translateY(-50%)";break;case 6:case 7:case 8:c.bottom=100-t+"%"}g.SP(this.element,c);if(this.S){M=this.j.offsetHeight;t=1;for(q=0;q<n.length;q++)c=n[q],typeof c.text==="string"&&(t+=c.text.split("\n").length-1,c.append||q===0||t++);M/=t;this.S.style.height=M+"px";this.S.style.width=M+"px";this.element.style.paddingLeft=M+5+"px";this.element.style.paddingRight=M+
5+"px";n=Number(this.element.style.marginLeft.replace("px",""))-M-5;M=Number(this.element.style.marginRight.replace("px",""))-M-5;this.element.style.marginLeft=n+"px";this.element.style.marginRight=M+"px"}};
g.X.iW=function(n){var q;for(q=0;q<n.length&&n[q]===this.D[q];q++);if(this.gJ||this.D.length>q)q=0,this.gJ=!1,this.D=[],this.N=this.aL=this.Fy=null,g.Jg(this.j);for(;q<n.length;q++)VJR(this,n[q])};
g.X.mO=function(){return 0};
g.X.C0=function(){return 0};
g.X.toString=function(){return g.ql.prototype.toString.call(this)};Bx.prototype.clear=function(){this.Z=this.time=this.mode=0;this.X=[];this.reset()};
Bx.prototype.reset=function(){this.mode=0;this.J.reset(0);this.j.reset(1)};
var Csj=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];DM.prototype.set=function(n){this.type=n};
DM.prototype.get=function(){return this.type};
AR.prototype.clear=function(){this.state=0};
AR.prototype.update=function(){this.state=this.state===2?1:0};
AR.prototype.Je=function(){return this.state!==0};
AR.prototype.matches=function(n,q){return this.Je()&&n===this.qH&&q===this.W$};
nxR.prototype.reset=function(){this.timestamp=this.X=0};
mL.prototype.updateTime=function(n){for(var q=1;q<=15;++q)for(var M=1;M<=32;++M)this.Z[q][M].timestamp=n};
mL.prototype.debugString=function(){for(var n="\n",q=1;q<=15;++q){for(var M=1;M<=32;++M){var t=this.Z[q][M];n=t.X===0?n+"_":n+String.fromCharCode(t.X)}n+="\n"}return n};
mL.prototype.reset=function(n){for(var q=0;q<=15;q++)for(var M=0;M<=32;M++)this.Z[q][M].reset();this.J=n;this.X=0;this.W=this.row=1};
var q5s=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],MCU=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],ieR=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],tCm=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];o3.prototype.reset=function(n,q){this.j=q;this.style.set(2);this.W=this.S;this.J=this.D;this.X=this.W;var M=(n<<2)+(q<<1);this.S.reset(M);this.D.reset(M);this.text.reset((n<<2)+(q<<1)+1)};
u5.prototype.reset=function(n){this.j=n;this.W.clear();this.J=this.Z;this.Z.reset(n,0);this.S.reset(n,1)};kKf.prototype.J=function(){};g.L(zI,g.OM);zI.prototype.toString=function(){return g.OM.prototype.toString.call(this)};g.L(JR,g.D);JR.prototype.reset=function(){};g.L(Vk,g.OM);Vk.prototype.toString=function(){return g.OM.prototype.toString.call(this)};
var CZ=0;g.L(ra,JR);ra.prototype.reset=function(){this.D={};this.W=this.X=null;this.S=!0};
ra.prototype.Z=function(n,q){n=n.firstChild;n.getAttribute("format");q=q||0;Number.isFinite(q);n=Array.from(n.childNodes);n=g.T(n);for(var M=n.next();!M.done;M=n.next())if(M=M.value,M.nodeType===1)switch(M.tagName){case "head":var t=M;break;case "body":var c=M}if(t)for(t=Array.from(t.childNodes),t=g.T(t),n=t.next();!n.done;n=t.next())if(n=n.value,n.nodeType===1)switch(n.tagName){case "pen":M=n.getAttribute("id");var Y=this.pens,G={},k=n.getAttribute("p");k&&Object.assign(G,this.pens[k]);k=Qk(n,"b");
k!=null&&(G.bold=k);k=Qk(n,"i");k!=null&&(G.italic=k);k=Qk(n,"u");k!=null&&(G.underline=k);k=pZ(n,"et");k!=null&&(G.charEdgeStyle=k);k=pZ(n,"of");k!=null&&(G.offset=k);k=qg(n,"bc");k!=null&&(G.background=k);k=qg(n,"ec");k!=null&&(G.m2=k);k=qg(n,"fc");k!=null&&(G.color=k);k=pZ(n,"fs");k!=null&&k!==0&&(G.fontFamily=k);k=xS(n,"sz");k!==void 0&&(G.fontSizeIncrement=k/100-1);k=xS(n,"bo");k!==void 0&&(G.backgroundOpacity=k/255);k=xS(n,"fo");k!==void 0&&(G.textOpacity=k/255);k=pZ(n,"rb");k!=null&&k!==10&&
k!==0&&(G.Hm=k>10?k-1:k);n=pZ(n,"hg");n!=null&&(G.JS=n);Y[M]=G;break;case "ws":M=n.getAttribute("id");this.T[M]=OeR(this,n);break;case "wp":M=n.getAttribute("id"),this.N[M]=gxa(this,n)}if(c){t=[];c=Array.from(c.childNodes);c=g.T(c);for(n=c.next();!n.done;n=c.next())if(n=n.value,n.nodeType===1)switch(n.tagName){case "w":this.X=eXd(this,n,q,!1);(n=this.D[this.X.id])&&n.end>this.X.start&&(n.end=this.X.start);this.D[this.X.id]=this.X;t.push(this.X);break;case "p":var b=n;k=q;M=[];Y=b.getAttribute("w")||
this.j;G=!!Qk(b,"a");k=(xS(b,"t")||0)+k;var d=xS(b,"d")||5E3;G||(!this.S&&this.W&&this.W.windowId===Y&&this.W.end>k&&(this.W.end=k),this.W&&this.W.text==="\n"&&(this.W.text=""));var N=G?6:5,O=b.getAttribute("p");O=O?this.pens[O]:null;var e=Array.from(b.childNodes);e.length&&(this.S=b.getAttribute("d")!=null);for(b=0;b<e.length;b++){var E=e[b],h=void 0;b>0&&(G=!0);var f=void 0;E.nodeType===1&&(f=E);if(f&&f.tagName==="s"){if((E=(E=f.getAttribute("p"))?this.pens[E]:null)&&E.Hm&&(E.Hm===1?(E=e.slice(b,
b+4),E.length===4&&(h=dVC(k,d,Y,G,N,E,this.pens),b+=3)):h=dVC(k,d,Y,G,N,[f],this.pens)),!h){var P=f;h=k;f=d;E=Y;var v=G,u=N,z=P.textContent?P.textContent:"",m=P.getAttribute("p");m=m?this.pens[m]:null;P=xS(P,"t")||0;h=new zI(h+P,f-P,u,E,z,v,m)}}else h=new zI(k,d,N,Y,E.textContent||"",G,O);M.push(h);this.W=h}if(M.length>0)for(M[0].windowId===this.j&&(this.X=eXd(this,n,q,!0),t.push(this.X)),n=g.T(M),M=n.next();!M.done;M=n.next())M=M.value,M.windowId=this.X.id,this.X.X.push(M),t.push(M)}q=t}else q=[];
return q};var VCs=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.L(Mg,JR);Mg.prototype.reset=function(){this.W.clear()};
Mg.prototype.Z=function(n,q){var M=JSON.parse(n);if(!M)return[];if(M.pens){n=0;for(var t=g.T(M.pens),c=t.next();!c.done;c=t.next()){c=c.value;var Y={},G=c.pParentId;G&&Object.assign(Y,this.X.get(G));c.bAttr&&(Y.bold=!0);c.iAttr&&(Y.italic=!0);c.uAttr&&(Y.underline=!0);G=c.ofOffset;G!=null&&(Y.offset=G);c.szPenSize!==void 0&&(Y.fontSizeIncrement=c.szPenSize/100-1);G=c.etEdgeType;G!=null&&(Y.charEdgeStyle=G);c.ecEdgeColor!==void 0&&(Y.m2=iF(c.ecEdgeColor));G=c.fsFontStyle;G!=null&&G!==0&&(Y.fontFamily=
G);c.fcForeColor!==void 0&&(Y.color=iF(c.fcForeColor));c.foForeAlpha!==void 0&&(Y.textOpacity=c.foForeAlpha/255);c.bcBackColor!==void 0&&(Y.background=iF(c.bcBackColor));c.boBackAlpha!==void 0&&(Y.backgroundOpacity=c.boBackAlpha/255);(G=c.rbRuby)&&G!==10&&(Y.Hm=G>10?G-1:G,Y.textEmphasis=VCs.get(Y.Hm));c.hgHorizGroup&&(Y.JS=c.hgHorizGroup);this.X.set(n++,Y)}}if(M.wsWinStyles)for(n=0,t=g.T(M.wsWinStyles),c=t.next();!c.done;c=t.next())c=c.value,Y={},(G=c.wsParentId)?Object.assign(Y,this.j.get(G)):Object.assign(Y,
this.S),c.mhModeHint!==void 0&&(Y.Pj=c.mhModeHint),c.juJustifCode!==void 0&&(Y.textAlign=c.juJustifCode),c.pdPrintDir!==void 0&&(Y.Fb=c.pdPrintDir),c.sdScrollDir!==void 0&&(Y.zm=c.sdScrollDir),c.wfcWinFillColor!==void 0&&(Y.windowColor=iF(c.wfcWinFillColor)),c.wfoWinFillAlpha!==void 0&&(Y.windowOpacity=c.wfoWinFillAlpha/255),this.j.set(n++,Y);if(M.wpWinPositions)for(n=0,t=g.T(M.wpWinPositions),c=t.next();!c.done;c=t.next())c=c.value,Y={},(G=c.wpParentId)&&Object.assign(Y,this.J.get(G)),c.ahHorPos!==
void 0&&(Y.PH=c.ahHorPos),c.apPoint!==void 0&&(Y.Tp=c.apPoint),c.avVerPos!==void 0&&(Y.Vh=c.avVerPos),c.ccCols!==void 0&&(Y.pR=c.ccCols),c.rcRows!==void 0&&(Y.Kx=c.rcRows),this.J.set(n++,Y);if(M.events){n=[];M=g.T(M.events);for(t=M.next();!t.done;t=M.next()){var k=t.value;c=(k.tStartMs||0)+q;Y=k.dDurationMs||0;if(k.id)G=String(k.id),t=Ex_(this,k,c,Y,G),n.push(t),this.W.set(G,t);else{k.wWinId?G=k.wWinId.toString():(G="_"+CZ++,t=Ex_(this,k,c,Y,G),n.push(t),this.W.set(G,t));t=n;var b=k;Y===0&&(Y=5E3);
k=this.W.get(G);var d=!!b.aAppend,N=d?6:5,O=b.segs,e=null;b.pPenId&&(e=this.X.get(b.pPenId));for(b=0;b<O.length;b++){var E=O[b],h=E.utf8;if(h){var f=E.tOffsetMs||0,P=null;E.pPenId&&(P=this.X.get(E.pPenId));if((k.params.Pj!=null?k.params.Pj:k.X.length>1?1:0)===2&&d&&h==="\n")continue;E=null;var v=[],u;if(u=P&&P.Hm===1){u=O;var z=b;if(z+3>=u.length||!u[z+1].pPenId||!u[z+2].pPenId||!u[z+3].pPenId)u=!1;else{var m=u[z+1].pPenId;(m=this.X.get(m))&&m.Hm&&m.Hm===2?(m=u[z+2].pPenId,m=this.X.get(m),!m||!m.Hm||
m.Hm<3?u=!1:(m=u[z+3].pPenId,u=(m=this.X.get(m))&&m.Hm&&m.Hm===2?!0:!1)):u=!1}}if(u)f=O[b+1].utf8,E=O[b+3].utf8,u=O[b+2].utf8,z=this.X.get(O[b+2].pPenId),h=bed(h,f,u,E,z),E=new zI(c,Y,N,G,h,d,P),b+=3;else{if(h.indexOf("<")>-1){var J=void 0;v=P;u=e;z=c;m=Y;var t_=f,C=N,gd=d,y1=[],h_=TI("<html>"+h+"</html>");if(!h_.getElementsByTagName("parsererror").length&&((J=h_.firstChild)==null?0:J.childNodes.length))for(J=g.T(h_.firstChild.childNodes),h_=J.next();!h_.done;h_=J.next()){h_=h_.value;var fa=void 0,
qR=void 0,GL=(qR=(fa=h_.textContent)==null?void 0:fa.replace(/\n/g,""))!=null?qR:"";if(h_.nodeType!==3||GL&&GL.match(/^ *$/)==null){fa={};Object.assign(fa,v||u);qR=void 0;switch((qR=h_)==null?void 0:qR.tagName){case "b":fa.bold=!0;break;case "i":fa.italic=!0;break;case "u":fa.underline=!0}y1.push(new zI(z+t_,m-t_,C,k.id,GL,gd,fa))}}v=y1}v.length||(v=[new zI(c+f,Y-f,N,k.id,h,d,P||e)])}if(v.length)for(d=g.T(v),P=d.next();!P.done;P=d.next())P=P.value,t.push(P),k.X.push(P);else E&&(t.push(E),k.X.push(E))}d=
!0}}}q=n}else q=[];return q};g.L(tD,I3);tD.prototype.Go=function(n,q,M){SrC(this.videoData.videoId,n.vssId,M.UA)};
tD.prototype.ql=function(n){if(this.audioTrack)for(var q=g.T(this.audioTrack.captionTracks),M=q.next();!M.done;M=q.next())SM(this.W,M.value);n.tB()};g.L(cw,l5);cw.prototype.iW=function(n){var q=this.W.X;l5.prototype.iW.call(this,n);for(n=n.length;n<q.length;n++){var M=q[n];if(Y&&M.X===c)var t=Y;else{t={};Object.assign(t,M.X);Object.assign(t,Cyd);var c=M.X;var Y=t}VJR(this,M,t)}};
var Cyd={K5:!0};g.L(Yf,kKf);Yf.prototype.J=function(n,q,M,t,c){if(M<t){var Y="_"+CZ++;M=M/1E3-this.S;t=t/1E3-this.S;n=new Vk(M,t-M,5,Y,{textAlign:0,Tp:0,PH:q*2.5,Vh:n*5.33});c=new zI(M,t-M,5,Y,c);this.W.push(n);this.W.push(c)}};
g.L(kf,JR);kf.prototype.Z=function(n){n=new Yf(n,n.byteLength,this.W);if(hXJ(n)){for(;n.byteOffset<n.X.byteLength;)for(n.version===0?n.Z=K2(n)*(1E3/45):n.version===1&&(n.Z=K2(n)*4294967296+K2(n)),n.j=Gh(n);n.j>0;n.j--){var q=Gh(n),M=Gh(n),t=Gh(n);q&4&&(q&3)===this.track&&(this.track===0||this.track===1)&&(q=this.X,q.X.push({time:n.Z,type:this.track,zH:M,GH:t,order:q.X.length}))}ppC(this.X,n);return n.W}return[]};
kf.prototype.reset=function(){this.X.clear()};g.L(bF,l5);g.X=bF.prototype;g.X.vD=function(){g.pO(this.qP)};
g.X.B2=function(){this.element.removeEventListener("transitionend",this.B2,!1);g.K4(this.element,"ytp-rollup-mode");this.dE(this.hq,!0)};
g.X.C0=function(){return this.J?this.U:this.T};
g.X.mO=function(){return this.J?this.T:this.U};
g.X.dE=function(n,q){this.hq=n;if(this.W.params.Kx){for(var M=0,t=0;t<this.D.length&&M<n.length;t++)this.D[t]===n[M]&&M++;M>0&&M<n.length&&(n=this.D.concat(n.slice(M)));this.g7=this.U;this.T=this.U=0;l5.prototype.dE.call(this,n);X0a(this,q)}l5.prototype.dE.call(this,n)};d7.prototype.unload=function(){this.X!=null&&(this.Q1.removeEventListener("sabrCaptionsDataLoaded",this.X),this.X=null);this.r7=[];this.Q1.Mm("sabrCaptionsBufferedRangesUpdated",this.r7)};
d7.prototype.j=function(n){return{formatId:g.YG(n.info.X.info,this.Wg),ut:n.info.ut+(this.Wg?0:1),startTimeMs:n.info.j*1E3,durationMs:n.info.N*1E3}};g.L(Ng,I3);Ng.prototype.Go=function(n,q,M){this.hP();q=n.getId();q=q!=null&&q in this.X.X?this.X.X[q]:null;q||(q=n.languageCode,q=this.X.isManifestless?Hek(this,q,"386"):Hek(this,q));q&&(this.J=n,this.S=q,IhC(this.D,M),this.Q1.Mm("sabrCaptionsTrackChanged",g.YG(q.info,this.X.Wg)))};
Ng.prototype.ql=function(n){var q=this.X.isManifestless?fhd(this,"386"):fhd(this);q=g.T(q);for(var M=q.next();!M.done;M=q.next())SM(this.W,M.value);n.tB()};
Ng.prototype.hP=function(){this.J&&(this.J=this.S=null,this.D.unload(),this.Q1.Mm("sabrCaptionsTrackChanged",null))};
Ng.prototype.XH=function(){return""};var Pyj="WEBVTT".split("").map(function(n){return n.charCodeAt(0)});
g.L(Oj,JR);
Oj.prototype.Z=function(n,q){n instanceof ArrayBuffer&&(n=g.N9(new Uint8Array(n)));var M=[];n=n.split(rXj);for(var t=1;t<n.length;t++){var c=n[t],Y=q;if(c!==""&&!xV_.test(c)){var G=vw.exec(c);if(G&&G.length>=4){var k=g7(G[1]),b=g7(G[2])-k;k+=Y;var d=(G=G[3])?G.split(" "):[];G={};var N=null;var O="";var e=null,E="";d=g.T(d);for(var h=d.next();!h.done;h=d.next())if(h=h.value.split(":"),h.length===2){var f=h[1];switch(h[0]){case "line":h=f.split(",");h[0].endsWith("%")&&(N=h[0],G.Vh=Number.parseInt(N,10),
h.length===2&&(O=h[1].trim()));break;case "position":h=f.split(",");e=h[0];G.PH=Number.parseInt(e,10);h.length===2&&(E=h[1].trim());break;case "align":switch(f){case "start":G.textAlign=0;break;case "middle":G.textAlign=2;break;case "end":G.textAlign=1}}}N||O||(O="end");if(!e)switch(G.textAlign){case 0:G.PH=0;break;case 1:G.PH=100;break;case 2:G.PH=50}if(G.textAlign!=null){N=0;switch(O){case "center":N+=3;break;case "end":N+=6;break;default:N+=0}switch(E){case "line-left":N+=0;break;case "center":N+=
1;break;case "line-right":N+=2;break;default:switch(G.textAlign){case 0:N+=0;break;case 2:N+=1;break;case 1:N+=2}}O=N<0||N>8?7:N;G.Tp=O}c=c.substring(vw.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");E=G;G=c;c={};if(G.indexOf("<")<0&&G.indexOf("&")<0)Y=lhd(k,b,5,E),b=new zI(k,b,5,Y.id,G,!1,g.Pl(c)?void 0:c),M.push(Y),M.push(b),Y.X.push(b);else for(O=G.split(QbJ),O.length===1?(G=5,E=lhd(k,b,G,E)):(N=G=6,E=Object.assign({pR:32},E),E=new Vk(k,b,N,"_"+CZ++,E)),M.push(E),N=k,e=0;e<O.length;e++)d=O[e],
e%2===0?(h=TI("<html>"+d+"</html>"),h.getElementsByTagName("parsererror").length?(f=h.createElement("span"),f.appendChild(h.createTextNode(d))):f=h.firstChild,To_(this,N,b-(N-k),G,E,e>0,f,c,M)):N=g7(d)+Y}vw.lastIndex=0}}return M};
var xV_=/^NOTE/,rXj=/(?:\r\n|\r|\n){2,}/,vw=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),QbJ=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.L(ev,g.D);ev.prototype.clear=function(){this.X&&this.X.dispose();this.X=null};
ev.prototype.reset=function(){this.X&&this.X.reset()};
ev.prototype.wJ=function(){g.D.prototype.wJ.call(this);this.clear()};var L2={windowColor:"#080808",windowOpacity:0,textAlign:2,Tp:7,PH:50,Vh:100,isDefault:!0,kQ:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.L(hD,g.P8);g.X=hD.prototype;g.X.wJ=function(){if(this.j||this.JE){var n=this.Q1.pn();n&&!n.pm()&&n.FR()}else Pw(this,!1);g.P8.prototype.wJ.call(this)};
g.X.S7=function(){if(this.Nm)return this.j||this.JE;var n=this.getAudioTrack();if(FPd(this)){if(!n.captionTracks.length)return!1;if(!this.W)return!0}n=Es(n,g.rq(this.Y));return n==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:n==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?y4(this):Ww(this)||y4(this)?!0:$Vu(this)};
g.X.load=function(){g.P8.prototype.load.call(this);this.T=this.getAudioTrack();if(this.W)this.X&&(this.Hb.clear(),this.j?ahs(this,!0):this.player.getPresentingPlayerType()!==3&&this.W.Go(this.X,"json3",this.d7),this.j||this.JE||jv(this)||this.player.p8("captionschanged",hR(this.X)));else{if(this.J==="OFFLINE")var n=new tD(this.player,this.videoData,this.getAudioTrack());else this.J==="SABR_LIVE"?n=new Ng(this.videoData.X,this.player):this.J==="LIVE"?n=new Px(this.videoData.X,this.player):this.J===
"INNERTUBE"?n=new fZ(this.player,this.videoData,this.getAudioTrack()):(n=this.videoData,n=new vx(this.player,this.videoData.hG,this.videoData.videoId,n.captionsLanguagePreference||n.B.captionsLanguagePreference||g.cc(n,"yt:cc_default_lang")||n.B.tE,this.videoData.o3,this.videoData.eventId));this.W=n;g.A(this,this.W);this.W.ql(this.d7)}};
g.X.unload=function(){if(this.j&&this.X)ahs(this,!1);else{if(this.aL){var n=this.aL;n.isActive()&&g.pO(n)}this.player.Ic("captions");this.Fy=[];this.W&&this.W.hP();this.Hb.clear();this.U&&this.player.aQ(this.U);this.mD()}g.P8.prototype.unload.call(this);this.player.kR();this.player.p8("captionschanged",{})};
g.X.create=function(){this.S7()&&this.load();var n;a:{var q,M,t;if(this.Y.G("web_player_nitrate_promo_tooltip")&&((q=this.videoData.getPlayerResponse())==null?0:(M=q.captions)==null?0:(t=M.playerCaptionsTracklistRenderer)==null?0:t.enableTouchCaptionsNitrate)){var c,Y;if(q=(n=this.videoData.getPlayerResponse())==null?void 0:(c=n.captions)==null?void 0:(Y=c.playerCaptionsTracklistRenderer)==null?void 0:Y.captionTracks)for(n=g.T(q),c=n.next();!c.done;c=n.next())if(c=c.value,c.kind==="asr"&&c.languageCode===
"en"){n=!0;break a}}n=!1}n&&this.Q1.Mm("showpromotooltip",this.D.element)};
g.X.tB=function(){var n=Es(this.player.getAudioTrack(),g.rq(this.Y));var q=n==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Xn(this,this.N):n==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&y4(this)?sj(this):Ww(this)||this.N||$Vu(this)?Xn(this,this.N):y4(this)?sj(this):null;if(this.j||this.JE){var M=this.W.W.X(!0);n=[];for(var t=0;t<M.length;t++){var c=M[t],Y=g.wJ("TRACK");Y.setAttribute("kind","subtitles");Y.setAttribute("label",g.dt(c));Y.setAttribute("srclang",g.bk(c));Y.setAttribute("id",c.toString());this.JE||
Y.setAttribute("src",this.W.XH(c,"vtt"));c===q&&Y.setAttribute("default","1");n.push(Y)}q=this.Q1.pn();q.fF(n);n=q.MM();this.Xh&&this.gJ.RL(n.textTracks,"change",this.VD)}else!this.X&&q&&Hw(this,q),this.player.p8("onCaptionsTrackListChanged"),this.player.bY("onApiChange")};
g.X.VD=function(){for(var n=this.Q1.pn().MM().textTracks,q=null,M=0;M<n.length;M++)if(n[M].mode==="showing")a:{q=this.W.W.X(!0);for(var t=0;t<q.length;t++)if(q[t].toString()===n[M].id){q=q[t];break a}q=null}(this.loaded?this.X:null)!==q&&Hw(this,q,!0)};
g.X.k0=function(){!this.X&&this.j||this.unload()};
g.X.UA=function(n,q,M,t){if(n){var c;f2(this,(c=this.X)!=null?c:void 0);this.W.OI()&&(this.Fy=[],this.Q1.Ic("captions"),yk(this.qm),this.Hb.reset());a:{c=this.Hb;t=t||0;M=ugu(c,n,M||0);n=[];try{for(var Y=g.T(M),G=Y.next();!G.done;G=Y.next()){var k=G.value,b=k.trackData,d=k.dN,N=c.Y.G("safari_live_drm_captions_fix");if(typeof b!=="string"){M=n;var O=M.concat;if(N&&vxf(b))var e=Boa(c,b,d);else{var E=c,h=q,f=b,P=d,v=t;if(!WPj(f))throw Error("Invalid binary caption track data");E.X||(E.X=new kf(v,h));
e=E.X.Z(f,P)}var u=O.call(M,e)}else{if(b.substring(0,6)==="WEBVTT")var z=n.concat(Boa(c,b,d));else{M=n;var m=M.concat;b:{h=E=void 0;f=c;P=q;if(b[0]==="{")try{f.X||(f.X=new Mg(DVR(P)));var J=h=f.X.Z(b,d);break b}catch(qR){g.P_(qR);J=[];break b}var t_=TI(b);if(!t_||!t_.firstChild){var C=Error("Invalid caption track data");C.params=b;throw C;}if(t_.firstChild.tagName==="timedtext"){if(Number(t_.firstChild.getAttribute("format"))===3){f.X||(f.X=new ra(DVR(P),f.Y));J=E=f.X.Z(t_,d);break b}var gd=Error("Unsupported subtitles format in web player (Format2)");
gd.params=b;throw gd;}if(t_.firstChild.tagName==="transcript"){var y1=Error("Unsupported subtitles format in web player (Format1)");y1.params=b;throw y1;}var h_=Error("Invalid caption track data");h_.params=b;throw h_;}z=m.call(M,J)}u=z}n=u}var fa=n;break a}catch(qR){c.logger.X(187101178,"Captions parsing failed: "+qR.message+". ");c.clear();fa=[];break a}fa=void 0}q=fa;q.length>0&&(fa=this.X,this.VA(fa,!!fa,jv(this)?"g":this.N?"m":"s"));this.player.aQ(q,void 0,this.J==="LIVE"||this.J==="SABR_LIVE");
!this.N||this.JE||jv(this)||g.Zw(this.Y)||g.aF(this.Y)||g.u2(this.Y)||this.Y.S==="shortspage"||this.player.isInline()||(q=this.aL,q.isActive()&&g.pO(q),q=Noj({Tp:0,PH:5,Vh:5,Kx:2,textAlign:0,Fb:1,lang:"ar"}),this.tE=[q],fa=["\u0627\u0646\u0642\u0631 \u0639\u0644\u0649 "," \u0644\u0644\u0648\u0635\u0648\u0644 \u0625\u0644\u0649 \u0627\u0644\u0625\u0639\u062f\u0627\u062f\u0627\u062a"],this.MP||(Y=new g.Qz({V:"svg",rJ:{height:"100%",version:"1.1",viewBox:"0 0 36 36",width:"100%"},jX:[{V:"path",SP:!0,
rJ:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.A(this,Y),this.MP=Y.element),Y=q.end-q.start,(G=g.dt(this.X))&&this.tE.push(new zI(q.start,Y,0,q.id,G)),this.tE.push(new zI(q.start,Y,0,q.id,fa[0]),new zI(q.start,Y,0,q.id,this.MP,!0),new zI(q.start,Y,0,q.id,fa[1],!0)),this.player.aQ(this.tE),g.Qx(this.aL));!this.N||this.JE||jv(this)||(g.rq(this.Y)?Sv(this,!0):Iu(this,!0),this.T&&(this.T.J=this.X),this.player.kR());this.N=!1}};
g.X.onCueRangeEnter=function(n){this.Fy.push(n);yk(this.qm)};
g.X.onCueRangeExit=function(n){g.TZ(this.Fy,n);this.W instanceof Px&&this.W.D&&this.player.OC([n]);yk(this.qm)};
g.X.getCaptionWindowContainerId=function(){return this.D.element.id};
g.X.O_=function(){JXC(this,this.tE);this.tE=null};
g.X.u8=function(){var n=this;if(!this.Fh||!this.j){this.qm.stop();g.vl(this.Cm);this.Fy.sort(g.gX);var q=this.Fy;if(this.U){var M=g.S4(q,function(Y){return this.U.indexOf(Y)===-1},this);
M.length&&(q=M)}q=g.T(q);for(M=q.next();!M.done;M=q.next())oxm(this,M.value);q=g.T(Object.entries(this.xl));var t=q.next();for(M={};!t.done;M={Xc:void 0,Xw:void 0},t=q.next()){var c=g.T(t.value);t=c.next().value;c=c.next().value;M.Xc=t;M.Xw=c;this.Cm[M.Xc]?(M.Xw.element.parentNode||(M.Xw instanceof bF||M.Xw instanceof cw||g.Wl(this.xl,function(Y){return function(G,k){k!==Y.Xc&&G.W.params.Tp===Y.Xw.W.params.Tp&&G.W.params.PH===Y.Xw.W.params.PH&&G.W.params.Vh===Y.Xw.W.params.Vh&&(G.dispose(),delete n.xl[k]);
return k===Y.Xc}}(M),this),this.D.element.appendChild(M.Xw.element)),M.Xw.dE(this.Cm[M.Xc])):(M.Xw.dispose(),delete this.xl[M.Xc])}}};
g.X.hT=function(){Ej(this,{},!0);this.player.p8("captionssettingschanged")};
g.X.Xs=function(){var n=L2.kQ;n={background:n.background,backgroundOpacity:n.backgroundOpacity,charEdgeStyle:n.charEdgeStyle,color:n.color,fontFamily:n.fontFamily,fontSizeIncrement:n.fontSizeIncrement,fontStyle:n.bold&&n.italic?3:n.bold?1:n.italic?2:0,textOpacity:n.textOpacity,windowColor:L2.windowColor,windowOpacity:L2.windowOpacity};var q=jM()||{};q.background!=null&&(n.background=q.background);q.backgroundOverride!=null&&(n.backgroundOverride=q.backgroundOverride);q.backgroundOpacity!=null&&(n.backgroundOpacity=
q.backgroundOpacity);q.backgroundOpacityOverride!=null&&(n.backgroundOpacityOverride=q.backgroundOpacityOverride);q.charEdgeStyle!=null&&(n.charEdgeStyle=q.charEdgeStyle);q.charEdgeStyleOverride!=null&&(n.charEdgeStyleOverride=q.charEdgeStyleOverride);q.color!=null&&(n.color=q.color);q.colorOverride!=null&&(n.colorOverride=q.colorOverride);q.fontFamily!=null&&(n.fontFamily=q.fontFamily);q.fontFamilyOverride!=null&&(n.fontFamilyOverride=q.fontFamilyOverride);q.fontSizeIncrement!=null&&(n.fontSizeIncrement=
q.fontSizeIncrement);q.fontSizeIncrementOverride!=null&&(n.fontSizeIncrementOverride=q.fontSizeIncrementOverride);q.fontStyle!=null&&(n.fontStyle=q.fontStyle);q.fontStyleOverride!=null&&(n.fontStyleOverride=q.fontStyleOverride);q.textOpacity!=null&&(n.textOpacity=q.textOpacity);q.textOpacityOverride!=null&&(n.textOpacityOverride=q.textOpacityOverride);q.windowColor!=null&&(n.windowColor=q.windowColor);q.windowColorOverride!=null&&(n.windowColorOverride=q.windowColorOverride);q.windowOpacity!=null&&
(n.windowOpacity=q.windowOpacity);q.windowOpacityOverride!=null&&(n.windowOpacityOverride=q.windowOpacityOverride);return n};
g.X.pM=function(n,q){var M={};Object.assign(M,jM());Object.assign(M,n);Ej(this,M,q);this.player.p8("captionssettingschanged")};
g.X.mD=function(){!this.j&&this.loaded&&(g.eN(this.xl,function(n,q){n.dispose();delete this.xl[q]},this),this.u8())};
g.X.NK=function(n,q){switch(n){case "fontSize":if(isNaN(q))break;n=g.kr(q,-2,4);this.pM({fontSizeIncrement:n});return n;case "reload":q&&!this.j&&Hw(this,this.X,!0);break;case "stickyLoading":q!==void 0&&(g.rq(this.Y)?Sv(this,!!q):Iu(this,!!q));break;case "track":return zXm(this,q);case "tracklist":return this.W?g.L$(this.W.W.X(!(!q||!q.includeAsr)),function(M){return hR(M)}):[];
case "translationLanguages":return this.W?this.W.j.map(function(M){return Object.assign({},M)}):[];
case "sampleSubtitles":this.j||q===void 0||Pw(this,!!q);break;case "sampleSubtitlesCustomized":this.j||Pw(this,!!q,q);break;case "recommendedTranslationLanguages":return g.PH();case "defaultTranslationSourceTrackIndices":return this.W?this.W.N:[]}};
g.X.getOptions=function(){var n="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");n.push("stickyLoading");return n};
g.X.Qq=function(){var n=this.X;if(this.Q1.o2("captions")){if(this.Y.G("html5_modify_caption_vss_logging")){var q;return(n=(q=this.videoData.M2)!=null?q:null)?{cc:g.pAa(n)}:{}}if(n)return q=n.vssId,n.translationLanguage&&q&&(q="t"+q+"."+g.bk(n)),{cc:q}}return{}};
g.X.yN=function(){this.isSubtitlesOn()?(g.rq(this.Y)?Sv(this,!1):Iu(this,!1),f2(this),Hw(this,null,!0)):this.UU()};
g.X.UU=function(){var n=jv(this)||!this.X?Xn(this,!0):this.X;n&&this.h1(n.vssId,"m");this.isSubtitlesOn()||Hw(this,jv(this)||!this.X?Xn(this,!0):this.X,!0)};
g.X.isSubtitlesOn=function(){return!!this.loaded&&!!this.X&&!jv(this)};
g.X.Qi=function(){var n=jv(this);y4(this,n)?Hw(this,this.getAudioTrack().X,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),FPd(this)&&(this.N=!1,this.X=null,this.W&&(this.W.dispose(),this.W=null)),this.S7()&&(n?Hw(this,Xn(this,!1),!1):this.load()))};
g.X.Da=function(n){n&&(this.Wb={top:n.top,right:n.right,bottom:n.bottom,left:n.left,width:1-n.left-n.right,height:1-n.top-n.bottom},this.D.element.style.top=this.Wb.top*100+"%",this.D.element.style.left=this.Wb.left*100+"%",this.D.element.style.width=this.Wb.width*100+"%",this.D.element.style.height=this.Wb.height*100+"%",this.D.element.style.position="absolute",n=w0U(this))&&(this.D.element.style.width=n.width+"px",this.D.element.style.height=n.height+"px")};
g.X.onVideoDataChange=function(n,q){n==="newdata"&&(this.videoData=q,this.loaded&&this.unload(),this.N=!1,this.X=null,this.W&&(this.W.dispose(),this.W=null,this.player.p8("captionschanged",{})),this.S7()&&this.load())};
g.X.getAudioTrack=function(){return this.player.getAudioTrack()};
g.X.gm=function(){var n=this.Q1.pn();n&&!n.pm()&&n.FR();this.Q1.isFullscreen()?(this.j=this.Nm=!0,this.loaded&&this.tB()):(this.Nm=this.Y.controlsType==="3",this.j=AXf(this));Hw(this,this.X)};
g.X.Xx=function(){var n,q,M,t=(n=this.videoData.getPlayerResponse())==null?void 0:(q=n.captions)==null?void 0:(M=q.playerCaptionsTracklistRenderer)==null?void 0:M.openTranscriptCommand;t&&this.player.Gk("innertubeCommand",t)};
g.X.VA=function(n,q,M){var t=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,c="";n&&(c=n.vssId,c=c.replace(t,""));var Y="";n&&n.getId()&&(Y=n.getId()||"");n&&n.getXtags()&&(n=n.getXtags(),n=n.replace(t,""),Y=Y.concat(";"+n));this.Q1.VA(q?c:"",q?Y:"",M)};
g.X.h1=function(n,q){n=(n||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");n.length>0&&this.Q1.h1(n,q)};g.LI("captions",hD);})(_yt_player);
